### ISSUE TITLE
cannot resolve module when execute packaged file

### ISSUE THREAD

**Issue by Einere** [vercel/pkg#1018]
# description

i made small node app using selenium.
i made executable file with ` pkg . -t node14-macos-x64`, it successful.
but packaged app log error when run it.
i think `pkg` cannot resolve module in dependency package.

# expected behavior

when run packaged file, run selenium.

# actual behavior
log error
```
Error: Cannot find module '../../../../bazel-genfiles/javascript/node/selenium-webdriver/lib/atoms/get-attribute.js'
Require stack:
- /snapshot/DCcleaner/node_modules/selenium-webdriver/lib/http.js
- /snapshot/DCcleaner/node_modules/selenium-webdriver/http/index.js
- /snapshot/DCcleaner/node_modules/selenium-webdriver/index.js
- /snapshot/DCcleaner/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1027:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:896:27)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at requireAtom (/snapshot/DCcleaner/node_modules/selenium-webdriver/lib/http.js:53:14)
    at Object.<anonymous> (/snapshot/DCcleaner/node_modules/selenium-webdriver/lib/http.js:35:22)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/DCcleaner/node_modules/selenium-webdriver/lib/http.js',
    '/snapshot/DCcleaner/node_modules/selenium-webdriver/http/index.js',
    '/snapshot/DCcleaner/node_modules/selenium-webdriver/index.js',
    '/snapshot/DCcleaner/index.js'
  ],
  pkg: true
}

...
```

# environment

### OS

MacOS Bug Sir v11.1

### pkg version

4.4.9
### package.json 
```json
{
    "name": "dccleaner",
    "version": "1.0.0",
    "description": "DCinside post cleaner",
    "main": "index.js",
    "scripts": {
        "start": "node index.js"
    },
    "author": "Einere",
    "license": "MIT",
    "dependencies": {
        "chromedriver": "^87.0.0",
        "selenium-webdriver": "^4.0.0-alpha.5"
    },
    "bin": {
        "DC_Cleaner": "./index.js"
    },
    "pkg": {
        "scripts": ["./*.js"],
        "assets": "./*"
    }
}
```
### index.js
```javascript
const {Builder, By} = require("selenium-webdriver");
const chrome = require("selenium-webdriver/chrome");
const chromeDriver = require("chromedriver");
const config = require("./config.js");

...
```

**Comment by jvictorsoto** [comment]
Forcing all scripts as asset will fix this.

include this on your package.json
```json
  "pkg": {
    "scripts": [
      "node_modules/selenium-webdriver/**/*.js"
    ]
  }

```

**Comment by polgiron** [comment]
I've been facing the same issue and @jvictorsoto solution fixed it, however I am now having an error regarding chromedriver "The ChromeDriver could not be found on the current PATH".

I've tried to add
```"node_modules/chromedriver/lib/chromedriver.js"```
or
```node_modules/chromedriver/bin/chromedriver```

into the scripts array but it doesn't work, anyone found a solution?
