### ISSUE TITLE
`pkg` fails when used with Bazel

### ISSUE THREAD

**Issue by rogermadjos** [vercel/pkg#1035]
I'm trying to use `pkg` in Bazel with no success. In my BUILD file:
```
load("@npm//pkg:index.bzl", "pkg")

pkg(
  name = "pkg",
  data = ["entrypoint"],
  outs = ["index"],
  args = [
    "-t",
    "linux",
    "-o",
    "entrypoint",
    "index.js",
  ],
)
```
When I run `bazel build`, I get the following errors:
```
ERROR: /------------------------------/projects/entrypoint/BUILD:37:4: Action projects/entrypoint/index failed (Exit 1): pkg.sh failed: error executing command bazel-out/host/bin/external/npm/pkg/bin/pkg.sh -t linux -o index index.js '--bazel_node_modules_manifest=bazel-out/k8-fastbuild/bin/projects/entrypoint/_pkg.module_mappings.json'

Use --sandbox_debug to see verbose messages from the sandbox pkg.sh failed: error executing command bazel-out/host/bin/external/npm/pkg/bin/pkg.sh -t linux -o index index.js '--bazel_node_modules_manifest=bazel-out/k8-fastbuild/bin/projects/entrypoint/_pkg.module_mappings.json'

Use --sandbox_debug to see verbose messages from the sandbox
/---------------/.cache/bazel/_bazel_-----------/4a71cbd3dfd8bb950b3d456ad1567d96/sandbox/linux-sandbox/8/execroot/ginto/node_modules/pkg-fetch/lib-es5/system.js:59
  var ldd = (0, _child_process.spawnSync)('ldd').stderr.toString();
                                                       ^

TypeError: Cannot read property 'toString' of null
    at detectAlpine (/--------------/.cache/bazel/_bazel_-------------/4a71cbd3dfd8bb950b3d456ad1567d96/sandbox/linux-sandbox/8/execroot/ginto/node_modules/pkg-fetch/lib-es5/system.js:59:56)
    at Object.<anonymous> (/--------------------/.cache/bazel/_bazel_----------/4a71cbd3dfd8bb950b3d456ad1567d96/sandbox/linux-sandbox/8/execroot/ginto/node_modules/pkg-fetch/lib-es5/system.js:65:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/--------------/.cache/bazel/_bazel_--------------/4a71cbd3dfd8bb950b3d456ad1567d96/sandbox/linux-sandbox/8/execroot/ginto/node_modules/pkg-fetch/lib-es5/index.js:17:38)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
```

**Comment by leerob** [comment]
Support for use with Bazel is out of scope (for trying to revive this library). I'm going to close this as won't fix, but if you end up doing a deep dive and figuring it out, I'm happy to review / merge PRs.
