### ISSUE TITLE
child_process.exec error

### ISSUE THREAD

**Issue by StreamerYT** [vercel/pkg#1057]
```js
child_process.exec(process.execPath,{env:{'invise':true}},(a,b,c)=>console.log(c))
```

```js
pkg/prelude/bootstrap.js:1340
      if (error.code !== 'MODULE_NOT_FOUND') throw error;
                                             ^

TypeError: Cannot read property 'charAt' of undefined
    at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:788:15)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1000:20)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1338:44)
    at Function.Module._load (internal/modules/cjs/loader.js:896:27)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:4
```

**Comment by abierbaum** [comment]
@StreamerYT I am seeing the same issue. Did you ever find a workaround?

**Comment by ErAz7** [comment]
any update on this?
maybe @jesec can help?
