### ISSUE TITLE
npm release?

### ISSUE THREAD

**Issue by carlo-quinonez** [vercel/pkg#1061]
There's been a lot of PR merged recently (thank you @leerob!) and I was wondering when the version of Pkg release on npmjs will go out?

**Comment by leerob** [comment]
Looks like there's a failing test that will need to be fixed first

```
/Users/leerobinson/Developer/pkg/test/test-50-for-await-of/main.js ok
assert.js:101
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'The value of "length" is out of range. It must be <= 5. Received 6'
- 'The value of "length" is out of range. It must be >= 0 && <= 5. Received 6'
                                                     ^
    at Object.<anonymous> (/Users/leerobinson/Developer/pkg/test/test-50-fs-runtime-layer-2/main.js:62:10)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 'The value of "length" is out of range. It must be <= 5. Received 6',
  expected: 'The value of "length" is out of range. It must be >= 0 && <= 5. Received 6',
  operator: 'strictEqual'
}
> node main.js node12
```

**Comment by carlo-quinonez** [comment]
When did it start failing?

**Comment by leerob** [comment]
I believe it's something with my local machine, maybe. I'm trying to debug, because the tests are passing in CI.

**Comment by david-mohr** [comment]
@leerob just hit this same error.  Looks like it's to do with minor differences in the local node output and the version of node packaged into the exe.  I've got a workaround you can use in #1066 . I also removed `copy-paste` as it just hangs when I try to run the test locally.  All other tests pass.

Let me know if you want the test fixes in a separate PR

**Comment by leerob** [comment]
I'm good to include the test fixes in that PR!

**Comment by leerob** [comment]
I did it! 🙏 🎉 

https://github.com/vercel/pkg/releases/tag/4.5.0
