### ISSUE TITLE
after-effects - issue

### ISSUE THREAD

**Issue by gersirami** [vercel/pkg#1067]
Hello!
I'm trying to pkg my script, i'm requiring [after-effects](https://github.com/BenZed/after-effects#readme) and the .exe doesn't work.
I get this error:

`SyntaxError: unknown: Unexpected token, expected , (1:23)
> 1 | (function () { [native code] })
    |                        ^
    at Parser.raise (D:\snapshot\Script\node_modules\babylon\lib\index.js:4454:13)
    at Parser.unexpected (D:\snapshot\Script\node_modules\babylon\lib\index.js:1761:8)
    at Parser.expect (D:\snapshot\Script\node_modules\babylon\lib\index.js:1749:33)
    at Parser.parseExprList (D:\snapshot\Script\node_modules\babylon\lib\index.js:4296:12)        
    at Parser.parseExprAtom (D:\snapshot\Script\node_modules\babylon\lib\index.js:3714:28)        
    at Parser.parseExprSubscripts (D:\snapshot\Script\node_modules\babylon\lib\index.js:3494:19)  
    at Parser.parseMaybeUnary (D:\snapshot\Script\node_modules\babylon\lib\index.js:3474:19)      
    at Parser.parseExprOps (D:\snapshot\Script\node_modules\babylon\lib\index.js:3404:19)
    at Parser.parseMaybeConditional (D:\snapshot\Script\node_modules\babylon\lib\index.js:3381:19)
    at Parser.parseMaybeAssign (D:\snapshot\Script\node_modules\babylon\lib\index.js:3344:19) {   
  pos: 23,
  loc: Position { line: 1, column: 23 },
  _babel: true,
  codeFrame: '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 1 | \x1B[39m(\x1B[36mfunction\x1B[39m () { [native code] })\n' +
    ' \x1B[90m   | \x1B[39m                       \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m'
}`

**Comment by leerob** [comment]
Please provide a reproducible example, thank you! 🙏
