### ISSUE TITLE
pkg does not include package.json in some cases, resulting in failing resolves.

### ISSUE THREAD

**Issue by xanonid** [vercel/pkg#1123]
pkg seems not to be able to resolve `requires` in all cases correctly.

Minimal example:

index.js:
```
const Either = require('fp-ts/Either')
```

package.json:
```
{
  "main": "index.js",
  "dependencies": {
    "fp-ts": "^2.9.5"
  }
}
```

Runs fine with `node index.js`, but not with `pkg`:
```
pkg/prelude/bootstrap.js:1359
      throw error;
      ^

Error: Cannot find module 'fp-ts/Either'
Require stack:
- /snapshot/testcase/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1459:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1338:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/snapshot/testcase/index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1433:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/snapshot/testcase/index.js' ],
  pkg: true
}
```

The reason could be that the file `node_modules/fp-ts/Either/package.json` using relative paths:
```
{
  "main": "../lib/Either.js",
  "module": "../es6/Either.js",
  "typings": "../lib/Either.d.ts",
  "sideEffects": false
}
```

Explictely adding `node_modules/fp-ts/Either/package.json` as asset (or using `require('fp-ts/lib/Either')`) works as workaround.

Versions:
pkg: 4.5.1
node: 12.18.1

**Comment by hacke2** [comment]
maybe use pkg.scripts in package.json

**Comment by colelawrence** [comment]
This appears to be an issue where `pkg` might be struggling to include these files that are in a parent directory of the `package.json` file.
