### ISSUE TITLE
Error: Cannot find module '/snapshot/gnome-mua-desktop-node/index.js'

### ISSUE THREAD

**Issue by maifeeulasad** [vercel/pkg#1152]
I'm trying to package my first node.js application with package. 

Here is the repository, I'm trying to build : https://github.com/maifeeulasad/gnome-mua-desktop-node

My command : **`pkg index.js`**

But the error I encounter is this : 
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/snapshot/gnome-mua-desktop-node/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1518:46)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1547:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by erossignon** [comment]
Your code is modern es6  and ECMAScript modules ( it uses import statements instead of requires) , At this time, I think that you will have to transpile your project to commonjs.

(as a side note: writeFile requires a explicit callback method
```
if (!fs.existsSync(configFile)) {
    fs.writeFile(configFile, "{\"validatedOrNot\":\"y\"}", ) // use fs.writeFileSync instead
}
```)

**Comment by jesec** [comment]
^

https://github.com/vercel/ncc can help here.

**Comment by Niek** [comment]
I have the same error, but only on binaries generated for `linux-arm64`, the `linux-x64` binaries work fine.

**Comment by movahhedi** [comment]
Same error. Transpiling To CommonJS didn't work.
