### ISSUE TITLE
why call child_process.execSync throw error , my use babel

### ISSUE THREAD

**Issue by au-top** [vercel/pkg#1159]
```
<ref *1> Error: spawnSync C:\Windows\system32\cmd.exe ENOENT
    at Object.spawnSync (internal/child_process.js:1067:20)
    at spawnSync (child_process.js:602:24)
    at Object.execSync (child_process.js:647:15)
    at Object.execSync (pkg/prelude/bootstrap.js:1693:30)
    at Object.commandAnalysis (D:\snapshot\blackWorm\dist\functions\commandAnalysis.js:86:59)
    at D:\snapshot\blackWorm\dist\index.js:22:52
    at Interface._onLine (readline.js:335:5)
    at Interface._line (readline.js:666:8)
    at Interface._ttyWrite (readline.js:1010:14)
    at ReadStream.onkeypress (readline.js:213:10) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync C:\\Windows\\system32\\cmd.exe',
  path: 'C:\\Windows\\system32\\cmd.exe',
  spawnargs: [ '/d', '/s', '/c', '"dir"' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

**Comment by au-top** [comment]
code is 
```

child_process.execSync("dir")

```

**Comment by au-top** [comment]
package file content
```

{
  "name": "newApp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.12.1",
    "@babel/core": "^7.12.3",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-typescript": "^7.12.1",
    "@types/express": "^4.17.11",
    "@types/node": "^14.14.20",
    "@types/ws": "^7.4.0",
    "@typescript-eslint/eslint-plugin": "^4.14.0",
    "@typescript-eslint/parser": "^4.14.0",
    "eslint": "^7.17.0",
    "typescript": "^4.0.5",
    "mocha": "^8.3.2"
  },
  "bin": "dist/index.js",
  "pkg":{
    "scripts": "dist/command/*.js",
    "targets": ["node14-win-x64"],
    "outputPath": "dist_pkg_c"
  },
  "dependencies": {
    "@babel/runtime-corejs2": "^7.12.5",
    "express": "^4.17.1"
  }
}


```

**Comment by robertsLando** [comment]
The error says `ENOENT` it means that for some reason that script could not be present in snapshot file system or the path is different (check readme to see the path inside a packaged project)

**Comment by au-top** [comment]
> The error says `ENOENT` it means that for some reason that script could not be present in snapshot file system or the path is different (check readme to see the path inside a packaged project)

What you mean is that this behavior causes dir to be invoked in the snapshot system.

**Comment by robertsLando** [comment]
@autop what's the path to the file you want to exec? In the script you provided I just see `"dir"`

**Comment by au-top** [comment]
thanks Is path problem
