### ISSUE TITLE
Error with Clipboardy module

### ISSUE THREAD

**Issue by TheBotlyNoob** [vercel/pkg#1181]
Running the windows or linux version returns:

```
C:\snapshot\math\node_modules\execa\index.js:347
                throw err;
                ^

Error: spawnSync C:\snapshot\math\node_modules\clipboardy\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at Object.spawnSync (internal/child_process.js:1067:20)
    at Object.spawnSync (child_process.js:602:24)
    at Object.spawnSync (pkg/prelude/bootstrap.js:1665:31)
    at Function.sync (C:\snapshot\math\node_modules\execa\index.js:334:30)
    at Object.copySync (C:\snapshot\math\node_modules\clipboardy\lib\windows.js:14:29)
    at C:\snapshot\math\node_modules\clipboardy\index.js:45:14
    at Object.<anonymous> (C:\snapshot\math\math.js)
    at Module._compile (pkg/prelude/bootstrap.js:1503:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync C:\\snapshot\\math\\node_modules\\clipboardy\\fallbacks\\windows\\clipboard_x86_64.exe',
  path: 'C:\\snapshot\\math\\node_modules\\clipboardy\\fallbacks\\windows\\clipboard_x86_64.exe',
  spawnargs: [ '--copy' ],
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'C:\\snapshot\\math\\node_modules\\clipboardy\\fallbacks\\windows\\clipboard_x86_64.exe --copy',
  timedOut: false
}
```

**Comment by TheBotlyNoob** [comment]
Fixed by https://github.com/vercel/pkg/issues/1160#issuecomment-833523252
