### ISSUE TITLE
Windows 10 builds linux-arm64 package error

### ISSUE THREAD

**Issue by 941477276** [vercel/pkg#1182]
## environment:
``` 
System: windows10
Node: v14.16.1
pkg: 5.1.0
```
## Error building `node-linux-arm64`
package.json
```
{
  "bin": "src/index.js",
  ...
  "devDependencies": {
    "pkg": "^5.1.0"
  },
  "pkg": {
    "scripts": [
      "src/**/*.js"
    ],
    "assets": [
      "src/crawler/configs/sql.sql",
      "src/php_IbcSYMEnc_data.sh"
    ],
    "targets": [
      "node14-linux-arm64"
    ]
  }
}
```
run: `pkg package.json`, the package was typed out, but it could not be executed, and I got an error
```
internal/child_process.js:403
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:553:9)
    at fabricate (E:\work\news_crawler\node_modules\pkg\lib-es5\fabricator.js:19:41)
    at Object.fabricateTwice (E:\work\news_crawler\node_modules\pkg\lib-es5\fabricator.js:84:5)
    at MultiStream._queue (E:\work\news_crawler\node_modules\pkg\lib-es5\producer.js:259:49)
    at MultiStream._next (E:\work\news_crawler\node_modules\multistream\index.js:86:12)
    at Meter.onEnd (E:\work\news_crawler\node_modules\multistream\index.js:129:12)
    at Object.onceWrapper (events.js:421:28)
    at Meter.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
```
How can I solve this problem?

**Comment by jesec** [comment]
Not possible. `pkg` will run the executable of the target architecture to generate bytecodes. 

Unfortunately, there is no way to run a `arm64` executable on a `x64` windows machine. 

(On Linux, it is possible with the assistance of an emulator like `QEMU`. On macOS, it is possible to build `x64` on `arm64` with the help of `Rosetta 2` but not reverse.)

Alternatively, you can choose to expose source codes and disable bytecode generation: `--no-bytecode --public-packages "*" --public`.

**Comment by 941477276** [comment]
Yes, it is possible to compile the arm64 package on the linux system
