### ISSUE TITLE
Unable to run tesseract.js

### ISSUE THREAD

**Issue by MacroChip** [vercel/pkg#1188]
https://github.com/MacroChip/tesseract-903 is a reproduction of the error, which was first reported as issue #903
Reproduce by running `npm t` then run resulting binary

Thank you very much!

**Comment by robertsLando** [comment]
@MacroChip Could you alsop attach here logs of the error?

**Comment by MacroChip** [comment]
@robertsLando 
```internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/home/chip/code/tesseract-903/--debug-port=9230'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1709:46)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1737:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by Tylerjet** [comment]
@MacroChip so i was running into this error as well, I seemed to have fixed it by going to `node_modules\tesseract.js\src\worker\node\spawnWorker.js` and deleting the exec arg so the file instead looks like
```
const { fork } = require('child_process');

/**
 * spawnWorker
 *
 * @name spawnWorker
 * @function fork a new process in node
 * @access public
 */
module.exports = ({ workerPath }) => {
  debugPort += 1;
  return fork(workerPath);
};
```

I'm unsure of what the debug port is really needed for but for at least my use case it did not affect much.

**Comment by Tylerjet** [comment]
@MacroChip so i was running into this error as well, I seemed to have fixed it by going to `node_modules\tesseract.js\src\worker\node\spawnWorker.js` and deleting the exec arg so the file instead looks like
```
const { fork } = require('child_process');

/**
 * spawnWorker
 *
 * @name spawnWorker
 * @function fork a new process in node
 * @access public
 */
module.exports = ({ workerPath }) => {
  return fork(workerPath);
};
```
I'm unsure of what the debug port is really needed for but for at least my use case it did not affect much.

I also see that there is a pull request about execArgv which is used in that file with child_process.fork. #1157 but unsure of the status of that atm.

**Comment by MacroChip** [comment]
@Tylerjet Thanks that worked for me. I was unsure how to debug this. Great investigation.

**Comment by carlosgalveias** [comment]
Just had the same issue when using pkg, any news on the fix?

**Comment by 3dprogramin** [comment]
Having a similar issue

"node": "v16.11.1"
"pkg": "5.8.0"
"tesseract.js": "3.0.3"


```javascript
node:internal/event_target:912
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module '/snapshot/scraper/node_modules/tesseract.js/src/worker-script/node/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:191:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
