### ISSUE TITLE
xcode-select: Failed to locate 'codesign_allocate'

### ISSUE THREAD

**Issue by nswbmw** [vercel/pkg#1201]
```sh
Big Sur 11.4 (20F71)

Darwin xxx.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

$ node -v
v14.17.0

$ npm -v
6.14.13

$ locate codesign_allocate
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate-p
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/codesign_allocate.1
/Library/Developer/CommandLineTools/usr/bin/codesign_allocate
/Library/Developer/CommandLineTools/usr/bin/codesign_allocate-p
/Library/Developer/CommandLineTools/usr/share/man/man1/codesign_allocate.1
/usr/bin/codesign_allocate
/usr/libexec/DeveloperTools/codesign_allocate
```

```
> pkg@5.2.1
> Targets not specified. Assuming:
  node14-linux-x64, node14-macos-x64, node14-win-x64
codesign_allocate: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find codesign_allocate 2> /dev/null' failed with exit code 256: (null) (errno=Invalid argument)
xcode-select: Failed to locate 'codesign_allocate', requesting installation of command line developer tools.
/Users/xxx/.pkg-cache/v3.1/fetched-v14.17.0-macos-x64-signed: the codesign_allocate helper tool cannot be found or used
> Error! Error: Command failed: codesign --sign - /Users/xxx/.pkg-cache/v3.1/fetched-v14.17.0-macos-x64-signed
codesign_allocate: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find codesign_allocate 2> /dev/null' failed with exit code 256: (null) (errno=Invalid argument)
xcode-select: Failed to locate 'codesign_allocate', requesting installation of command line developer tools.
/Users/xxx/.pkg-cache/v3.1/fetched-v14.17.0-macos-x64-signed: the codesign_allocate helper tool cannot be found or used

    at checkExecSyncError (child_process.js:640:11)
    at Object.execSync (child_process.js:676:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/pkg/lib-es5/index.js:583:37)
    at step (/usr/local/lib/node_modules/pkg/lib-es5/index.js:45:23)
    at Object.next (/usr/local/lib/node_modules/pkg/lib-es5/index.js:26:53)
    at fulfilled (/usr/local/lib/node_modules/pkg/lib-es5/index.js:17:58)f
```

**Comment by jesec** [comment]
Make sure that `codesign` is runnable.

Due to the new [mandatory code signing requirement](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes), `pkg` will attempt to sign the base executable to run it to generate bytecodes, and sign the final executable to make it work on new platforms.

**Comment by nswbmw** [comment]
codesign is runnable.

```sh
$ codesign
Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
       codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
       codesign -d [options] path ... # display contents
       codesign -h pid ... # display hosting paths
```

**Comment by nswbmw** [comment]
Solved by [https://stackoverflow.com/a/19529693](https://stackoverflow.com/a/19529693)
