### ISSUE TITLE
Node 12 fails with internalModuleReadJSON is not a function

### ISSUE THREAD

**Issue by markus456** [vercel/pkg#1209]
I'm running a mocha test that calls a command from an executable built with pkg to check that the system is up and running. 
When pkg is used with node10, it works as expected and the command succeeds. With node12 or node14, the command starts failing with the following error: 
```
internal/modules/package_json_reader.js:4
const internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };
                                                                   ^

TypeError: require(...).internalModuleReadJSON is not a function
    at internalModuleReadJSON (internal/modules/package_json_reader.js:4:68)
    at Object.read (internal/modules/package_json_reader.js:19:34)
    at readPackage (internal/modules/cjs/loader.js:237:36)
    at readPackageScope (internal/modules/cjs/loader.js:270:19)
    at trySelf (internal/modules/cjs/loader.js:386:40)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:24)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1147:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:451:5)

      at ChildProcess.exithandler (child_process.js:319:12)
      at maybeClose (internal/child_process.js:1055:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```
Oddly enough, when I execute the same command from the command line, it works just fine. So far I haven't been able to reproduce the problem when executing commands manually and I could use dome help in understand exactly why it behaves like it does.

Tested with both pkg@5.1.0 and pkg@5.2.1 and both seem to behave the same way.

**Edit:** I think I've managed to narrow the possible cause to be the `nyc` wrapper that we use for `mocha` to get code coverage metrics. With just `mocha`, this problem seems to go away. This suggests that whatever `nyc` does propagates down through the `child_process.execFile` call we used to run a script that runs the program packaged with pkg.

**Comment by jesec** [comment]
You may not pass Node.js command line arguments (e.g. `--prof-process`) to the program packaged with `pkg`. The executable is not debuggable or inspectable.

**Comment by markus456** [comment]
We don't pass any arguments to nodejs and running the script that calls the command manually seems to work just fine. Are there some environment variables that might affect this?

**Comment by jesec** [comment]
https://github.com/vercel/pkg#error-requireinternalmodulestat-is-not-a-function

**Comment by jesec** [comment]
To collect code coverage, almost certainly the caller passes unsupported Node options.

**Comment by markus456** [comment]
Ah, that makes perfect sense. I'll edit the original report with the steps to prevent this and close this issue.
