### ISSUE TITLE
PM2: Unexpected token (3:0)

### ISSUE THREAD

**Issue by dimitribocquet** [vercel/pkg#1213]
I'm trying to use pkg with pm2, to serve my ExpressJS app, and when I run `pkg package.json -t macos` I got this error:

```
pkg package.json -t macos

> pkg@5.1.0
> Error! Unexpected token (3:0)
  /Users/dimitribocquet/Sites/nodejs-app/node_modules/pm2-deploy/deploy
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nodejs-app@1.1.2 pack: `pkg package.json -t macos`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nodejs-app@1.1.2 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dimitribocquet/.npm/_logs/2021-06-07T09_51_11_686Z-debug.log
```

in the debug.log file:
```
10 silly lifecycle nodejs-app@1.1.2~pack: Args: [ '-c', 'pkg package.json -t macos' ]
11 silly lifecycle nodejs-app@1.1.2~pack: Returned: code: 2  signal: null
12 info lifecycle nodejs-app@1.1.2~pack: Failed to exec pack script
13 verbose stack Error: nodejs-app@1.1.2 pack: `pkg package.json -t macos`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/dimitribocquet/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/dimitribocquet/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

Everything works well when I manually run `pm2-runtime start index.js`.

I'm not sure to use it on the right way, so feel free to correct me:

package.json:
```
{
    "name": "nodejs-app",
    "version": "1.1.2",
    "description": "",
    "main": "index.js",
    "bin": "index.js",
    "scripts": {
      "start": "pm2-runtime start index.js",
      "pack": "pkg package.json -t macos"
    },
    "pkg": {
      "outputPath": "dist",
      "assets": [
        "views/**/*",
        "./.env"
      ],
      "options": {}
    },
    "directories": {
      "test": "./test"
    }
    ...
  }
  ```

index.js  
```
var pm2 = require('pm2');
const config = require('./config');

pm2.connect(function(err) {
  if (err) {
    console.error(err);
    process.exit(2);
  }
  
  pm2.start({
    name : 'nodejs-app',
    script    : 'app.js',
    exec_mode : 'cluster',
    instances : 1,
    max_memory_restart : '100M'
  }, function(err, apps) {
    if (err) throw err
  });
});
```

**Comment by kennylbj** [comment]
+1, any solution for this?

**Comment by ryanemax** [comment]
+1, any solution for this?

**Comment by flyweights** [comment]
+1, any solution for this?
