### ISSUE TITLE
shed more light on process exit 4

### ISSUE THREAD

**Issue by ozsay** [vercel/pkg#1217]
We are packing a CLI tool using `pkg` and we see that on some machines, the binary exits with code 4.

I saw this https://github.com/vercel/pkg/blob/master/prelude/bootstrap.js#L1505

I'm wondering on the possible reasons why it would happen.

we are building the binary on a linux machine (for both linux and macos).

Binary works on the linux machines but fails on some macos machines.

**Comment by pojntfx** [comment]
Can reproduce this; see #1194 :+1: 

```shell
pojntfx@bd5326fa913b:~/Projects/grpc-examples/mather.js/testing$ pkg -t host main.js 
> pkg@5.2.1
pojntfx@bd5326fa913b:~/Projects/grpc-examples/mather.js/testing$ ./main 
pojntfx@bd5326fa913b:~/Projects/grpc-examples/mather.js/testing$ echo $?
4
pojntfx@bd5326fa913b:~/Projects/grpc-examples/mather.js/testing$ export NODE_OPTIONS="--max_old_space_size=4096 --trace-exit"
pojntfx@bd5326fa913b:~/Projects/grpc-examples/mather.js/testing$ ./main 
(node:2980) WARNING: Exited the environment with code 4
    at exit (internal/process/per_thread.js:174:13)
    at _compile (pkg/prelude/bootstrap.js:1682:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Module._load (internal/modules/cjs/loader.js:774:14)
    at runMain (pkg/prelude/bootstrap.js:1739:12)
    at internal/main/run_main_module.js:17:47
pojntfx@bd5326fa913b:~/Projects/grpc-examples/mather.js/testing$ export NODE_OPTIONS=--max_old_space_size=4096
pojntfx@bd5326fa913b:~/Projects/grpc-examples/mather.js/testing$ export NODE_OPTIONS=""
pojntfx@bd5326fa913b:~/Projects/grpc-examples/mather.js/testing$ ./main 
Hello, world!
```
