### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string.

### ISSUE THREAD

**Issue by z-inc** [vercel/pkg#1229]
Error on render an EJS template

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number (0)
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:154:9)
    at Object.process.pkg.path.resolve (pkg/prelude/bootstrap.js:477:25)
    at View.lookup (E:\snapshot\pk\node_modules\express\lib\view.js:114:32)
    at new View (E:\snapshot\pk\node_modules\express\lib\view.js:94:20)
    at Function.render (E:\snapshot\pk\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (E:\snapshot\pk\node_modules\express\lib\response.js:1012:7)
    at E:\snapshot\pk\src\server.js:47:9
    at Layer.handle [as handle_request] (E:\snapshot\pk\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\snapshot\pk\node_modules\express\lib\router\route.js:137:13)`
    
Code at:
./server.js:49
`...
app.set('views', path.resolve(__dirname, '../views/'));

app.get('/', function (req, res, next) {
    res.render('home.ejs');
})`

**Comment by petersem** [comment]
What was the resolution?
