### ISSUE TITLE
aws-crt native module 

### ISSUE THREAD

**Issue by zhex900** [vercel/pkg#1232]
I have a problem building with `aws-crt`. Related with #305 

Is it because it cannot find the `.node` ?

Node version should be the same. I manually build `aws-crt` and copied the `dist` to `node_modules/aws-crt/` 
```
PS C:\Code\mir-kiosk-electron\windowsSockets> .\build\ipc.exe
pkg/prelude/bootstrap.js:1614
      throw error;
      ^

Error: A dynamic link library (DLL) initialization routine failed.
C:\Users\jake\AppData\Local\Temp\4bd576e0be013fc17b3435d1d2f437566cd6c8d6e7cf10ae83871dfe22fc55b9\aws-crt-nodejs.node
    at tryImporting (pkg/prelude/bootstrap.js:1969:37)
    at tryImporting (pkg/prelude/bootstrap.js:2021:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2044:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module.require (pkg/prelude/bootstrap.js:1593:31)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\snapshot\windowsSockets\node_modules\aws-crt\dist\native\binding.js:55:19)
PS C:\Code\mir-kiosk-electron\windowsSockets>
````

````
// dist\native\binding.js
for (const path of search_paths) {
    if (path && fs_1.existsSync(path + '.node')) {
        binding = require(path);  //line 55
        break;
    }
}
````

````
//package.json
  "pkg": {
    "assets": [
      "./node_modules/aws-crt/dist/bin",
      "./node_modules/aws-crt/dist/include"
    ],
    "targets": [
      "node14-win-x64"
    ],
    "outputPath": "build"
  }
````

**Comment by patson12** [comment]
hii,
i used aws-iot-device-sdk version 1 in node js .. its working fine in source code. after making pkg and run then it wont connect. if you have any solutions please help

**Comment by mikelpr** [comment]
still a thing why is the windows factor a thing
