### ISSUE TITLE
Pkg crashes as soon as I open

### ISSUE THREAD

**Issue by CarsonLenze** [vercel/pkg#1234]
I turned a Node JS file into a .exe with PKG and when I run it it automatically crashes. When I run it with node . it works, and when I create a new file that only console logs "text" the new .exe works fine. This is the code im working with https://sourceb.in/Gg20KBfQFC

**Comment by erossignon** [comment]
* Which version of pkg are you using ?
* what is the version of node.js ?
* what command was used to create the pkg ?
* on which OS ? linux - windows - alpine etc ?

**Comment by Call-Me-Carson** [comment]
Which version of pkg are you using ?
7.3.0
what is the version of node.js ?
v14.16.1
what command was used to create the pkg ?
pkg index.js
on which OS ? linux - windows - alpine etc ?
Windows 10, version 20H2

**Comment by robertsLando** [comment]
@Call-Me-Carson Latest version of pkg is 5.3.0 so 7.3.0 isn't valid

**Comment by Call-Me-Carson** [comment]
I meant to put 5.3.0 sorry

**Comment by Call-Me-Carson** [comment]
Any ideas about why it's not working/ what I should try

**Comment by waikiki-bn** [comment]
@Call-Me-Carson

First I want to say, that i have used pkg only 2 times, maybe I am wrong.

Perhaps your code is working, just the exe file is closed after executing the code?
I have just got the same issue. I builded an exe file just to be sure, that I had configured everything correctly. In my code there was only 1 line -> console.log("Hello").

After I added some logic with express (just simple express server), my exe didn't close after i opened it.

**Comment by erossignon** [comment]
@Call-Me-Carson 
the code provided output this (when run with node)

```` 
 _____               _      _                     _           _____              _                       _____  _           _
|_   _|             (_)    | |                   | |         /  __ \            | |                     /  ___|| |         | |
  | |   _ __    ___  _   __| |  ___  _ __   __ _ | |_   ___  | /  \/ _   _  ___ | |_   ___   _ __ ___   \ `--. | |_   __ _ | |_  _   _  ___
  | |  | '_ \  / __|| | / _` | / _ \| '__| / _` || __| / _ \ | |    | | | |/ __|| __| / _ \ | '_ ` _ \   `--. \| __| / _` || __|| | | |/ __|
 _| |_ | | | || (__ | || (_| ||  __/| |   | (_| || |_ |  __/ | \__/\| |_| |\__ \| |_ | (_) || | | | | | /\__/ /| |_ | (_| || |_ | |_| |\__ \
 \___/ |_| |_| \___||_| \__,_| \___||_|    \__,_| \__| \___|  \____/ \__,_||___/ \__| \___/ |_| |_| |_| \____/  \__| \__,_| \__| \__,_||___/



 _   __                     _____  _      _        _____                      ______                _____  _             _____  _           _                 _____          _____  _                        _   _
| | / /                    |_   _|| |    (_)      |  _  |                     |  ___|              |_   _|| |           /  ___|| |         | |               |_   _|        /  ___|| |                      | | | |
| |/ /   ___   ___  _ __     | |  | |__   _  ___  | | | | _ __    ___  _ __   | |_     ___   _ __    | |  | |__    ___  \ `--. | |_   __ _ | |_  _   _  ___    | |    ___   \ `--. | |__    ___  __      __ | | | | _ __
|    \  / _ \ / _ \| '_ \    | |  | '_ \ | |/ __| | | | || '_ \  / _ \| '_ \  |  _|   / _ \ | '__|   | |  | '_ \  / _ \  `--. \| __| / _` || __|| | | |/ __|   | |   / _ \   `--. \| '_ \  / _ \ \ \ /\ / / | | | || '_ \
| |\  \|  __/|  __/| |_) |   | |  | | | || |\__ \ \ \_/ /| |_) ||  __/| | | | | |    | (_) || |      | |  | | | ||  __/ /\__/ /| |_ | (_| || |_ | |_| |\__ \   | |  | (_) | /\__/ /| | | || (_) | \ V  V /  | |_| || |_) |
\_| \_/ \___| \___|| .__/    \_/  |_| |_||_||___/  \___/ | .__/  \___||_| |_| \_|     \___/ |_|      \_/  |_| |_| \___| \____/  \__| \__,_| \__| \__,_||___/   \_/   \___/  \____/ |_| |_| \___/   \_/\_/    \___/ | .__/
                   | |                                   | |
                                                | |
                   |_|                                   |_|
                                                |_|

Error: Could not connect
    at Socket.onerror (/home/etienne/pkg/ttt/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:483:26)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```` 

and produces (when packed with `pkg index.js -t host` )

```
/snapshot/ttt/node_modules/ascii-art-font/font.js:73
                if(error) throw(error);
                          ^

Error: File '/**/ttt/node_modules/ascii-art-font/Fonts/Doom.flf' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:557:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:949:29)
    at Object.readFile (pkg/prelude/bootstrap.js:1020:5)
    at Object.loadFont (/snapshot/ttt/node_modules/ascii-art-font/font.js:72:16)
    at Object.parseFont (/snapshot/ttt/node_modules/ascii-art-font/font.js:34:34)
    at Object.write (/snapshot/ttt/node_modules/ascii-art-font/font.js:78:29)
    at Object.create (/snapshot/ttt/node_modules/ascii-art-font/font.js:144:29)
    at Object.<anonymous> (/snapshot/ttt/index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
  errno: -2,
  code: 'ENOENT',
  path: '/snapshot/ttt/node_modules/ascii-art-font/Fonts/Doom.flf',
  pkg: true
}
```

You need to explicitly add the ascii-art-font to the package.

This can be done by adding a `pkg` section to your package.json with a `"assets"` property such as :

`package.json`
```` 
{
  "name": "issue1234",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ascii-art-font": "^1.0.2",
    "chalk": "^4.1.1",
    "discord-rpc": "^4.0.1"
  },
  "bin": "./index.js",
  "pkg": {
      "scripts": "index.js",
      "assets": "node_modules/ascii-art-font/**/*"

   }
}
````

and un 

`pkg package.json -t host`

the file produced will be named with the name of your package , here test1234, and output will be as expected.

**Comment by denecirbv** [comment]
@CarsonLenze use this in the end of the file:
`process.stdin.resume();`
