### ISSUE TITLE
TypeError: Cannot destructure property `isRegExp` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by gstepniewski** [vercel/pkg#1235]
Getting this error when running a package built with pkg 5.3.0:

```
pkg/prelude/bootstrap.js:23
const { isRegExp } = require('util').types;
        ^

TypeError: Cannot destructure property `isRegExp` of 'undefined' or 'null'.
    at __importDefault.default (pkg/prelude/bootstrap.js:23:37)
    at pkg/prelude/bootstrap.js:2110:3
    at readPrelude (bootstrap_node.js:148:16)
    at bootstrap_node.js:153:22
    at bootstrap_node.js:160:8
    at startup (bootstrap_node.js:161:6)
    at bootstrap_node.js:661:3
```

It was definitely working yesterday with pkg 5.2.1, not sure how to get more information to help with debugging this?

**Comment by robertsLando** [comment]
@erossignon regression?

**Comment by erossignon** [comment]
Strange , this destructuring is supposed to work on all supported nodejs version:

````
$nvm use 10
Now using node v10.21.0 (npm v6.14.7)
$node -e "const { isRegExp1 } = require('util').types; console.log(typeof isRegExp1);"
undefined
$nvm use 10
Now using node v10.21.0 (npm v6.14.7)
$node -e "const { isRegExp } = require('util').types; console.log(typeof isRegExp);"
function
$nvm use 12
Now using node v12.22.1 (npm v6.14.12)
$node -e "const { isRegExp } = require('util').types; console.log(typeof isRegExp);"
function
$nvm use 14
Now using node v14.17.0 (npm v6.14.13)
$node -e "const { isRegExp } = require('util').types; console.log(typeof isRegExp);"
function
$nvm use 16
Now using node v16.4.0 (npm v7.18.1)
$node -e "const { isRegExp } = require('util').types; console.log(typeof isRegExp);"
function
````

**Comment by erossignon** [comment]
@gstepniewski  what is the exact step to reproduce ( please provide the smallest possible example)

**Comment by gstepniewski** [comment]
Looks like a problem with node 8:

```
[~] node -v                                                                                                                                                                                                                                                          
v8.17.0
[~] node -e "const { isRegExp1 } = require('util').types; console.log(typeof isRegExp1);"                                                                                                                                                                            
[eval]:1
const { isRegExp1 } = require('util').types; console.log(typeof isRegExp1);
        ^

TypeError: Cannot destructure property `isRegExp1` of 'undefined' or 'null'.
    at [eval]:1:38
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:653:30)
    at evalScript (bootstrap_node.js:479:27)
    at startup (bootstrap_node.js:180:9)
    at bootstrap_node.js:625:3
```

Is it not supported anymore?

**Comment by erossignon** [comment]
Yes, I confirm the type structure didn't exist in old nodejs 8.
nodejs 8 has reached end-of-life end on the 31st 12/2019. Your options would be to use an old version of pkg and is not recommended to be used in production anymore.

**Comment by gstepniewski** [comment]
Got it.
Thank you for looking into this!

**Comment by ventr1x** [comment]
I have the exact problem with node 14 though.
node -v
v14.17.1

**Comment by erossignon** [comment]
@ventr1x , it works for me,

```
C:\>node
Welcome to Node.js v14.17.6.
Type ".help" for more information.
> const { isRegExp } = require('util').types;
undefined
> isRegExp
[Function: isRegExp]
>
````

**Comment by klues** [comment]
Just trying to get the [express example](https://github.com/vercel/pkg/tree/main/examples/express) of this repository running, but I'm getting exactly this error:
```
$ pkg -v
5.5.2
$ node -v
v16.13.2
cd pkg/examples/express
npm install
$ pkg .
> pkg@5.5.2
$ ./express-example.exe
pkg/prelude/bootstrap.js:23
const { isRegExp } = require('util').types;
        ^

TypeError: Cannot destructure property `isRegExp` of 'undefined' or 'null'.
    at __importDefault.default (pkg/prelude/bootstrap.js:23:37)
    at pkg/prelude/bootstrap.js:2118:3
    at readPrelude (bootstrap_node.js:148:16)
    at bootstrap_node.js:153:22
    at bootstrap_node.js:160:8
    at startup (bootstrap_node.js:161:6)
    at bootstrap_node.js:661:3
```

However `node index.js` works without problems.
