### ISSUE TITLE
window new drive error on nas drive

### ISSUE THREAD

**Issue by hughdev** [vercel/pkg#1278]
pkg version 5.3.1

            const x = fs.statSync(path.resolve("Z:\\", ""))

Error: File or directory 'Z:**' was not included into executable at compilation stage. Please recompile adding it as asset or script.
at error_ENOENT (pkg/prelude/bootstrap.js:557:19)
at findNativeAddonForStat (pkg/prelude/bootstrap.js:1271:32)
at statFromSnapshot (pkg/prelude/bootstrap.js:1294:25)
at Object.statSync (pkg/prelude/bootstrap.js:1308:12)
at C:\snapshot\test\local-space.service.js
at Array.forEach ()
at LocalSpaceService.getLocalFSInfo (C:\snapshot\test\local-space.service.js)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async LocalSpaceController.fun (C:\snapshot\test\local-space.controller.js) {
errno: -4058,
code: 'ENOENT',
path: 'Z:\snapshot',
pkg: true
}

{
  "pkg": {
    "scripts": [
      "Z:\\"
    ],
    "assets": [
      "Z:\\"
    ]
  }
}

**Comment by hughdev** [comment]
{
  "pkg": {
    "scripts": [
      "Z:\\"
    ],
    "assets": [
      "Z:\\"
    ]
  }
}

**Comment by hughdev** [comment]
Z:\\snapshot what is it?
