### ISSUE TITLE
sqlite3 'ERR_DLOPEN_FAILED' at pkg/prelude/bootstrap.js

### ISSUE THREAD

**Issue by browningluke** [vercel/pkg#1288]
Hi there,
I'm trying to create a packaged app with sequelize and sqlite3, but I keep getting the following error.

I've tried moving the `sqlite3.node` file to the same directory as the complied binary, but it still throws the same error.

```
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: dlopen(/Users/lukebrowning/Documents/dev/build/test/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node, 1): Symbol not found: _napi_create_error
  Referenced from: /Users/lukebrowning/Documents/dev/build/test/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node
  Expected in: flat namespace
 in /Users/lukebrowning/Documents/dev/build/test/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node
    at process.dlopen (pkg/prelude/bootstrap.js:2105:30)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1154:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/snapshot/test/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

I am trying to modify a file outside of the snapshot (as below).

```ts
console.log(path.join(os.homedir(), '.test/database.sqlite'));

const sequelize = new Sequelize({
    dialect: 'sqlite',
    storage: path.join(os.homedir(), '.test/database.sqlite'),
    logging: false,
});
```

Any help would be much appreciated.
Thank you

**Comment by browningluke** [comment]
I just checked to ensure I had the same node version installed for my system-wide as what I was targeting.

My package.json pkg config is this:
```
"pkg": {
    "scripts": "dist/**/*.js",
    "targets": [
      "node14-macos-x64"
    ],
    "assets": "node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node",
    "outputPath": "."
  },
```

Any my node version is this:
```
$ node -v
v14.17.2
```

But I still get an error like this:
```
Error: dlopen(/var/folders/ph/33dgq_qx7xz0gnvh2slzwpwm0000gn/T/eb0b5da7dcc8fd62c75fb49c1ad15ff8352e68b528a995e028b455f26913f7c5/node_sqlite3.node, 1): Symbol not found: _napi_create_error
  Referenced from: /var/folders/ph/33dgq_qx7xz0gnvh2slzwpwm0000gn/T/eb0b5da7dcc8fd62c75fb49c1ad15ff8352e68b528a995e028b455f26913f7c5/node_sqlite3.node
  Expected in: flat namespace
 in /var/folders/ph/33dgq_qx7xz0gnvh2slzwpwm0000gn/T/eb0b5da7dcc8fd62c75fb49c1ad15ff8352e68b528a995e028b455f26913f7c5/node_sqlite3.node
    at tryImporting (pkg/prelude/bootstrap.js:2028:37)
    at tryImporting (pkg/prelude/bootstrap.js:2080:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/snapshot/test/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
```

Thanks once again.

**Comment by AmeliaPessoa** [comment]
Hi, @browningluke, some news about it?

I also have this error using `node v16.11.1`.

Even trying the @KirinPeng suggestion.

**Comment by labsphere-mws** [comment]
Having the same issue as well. Does not appear to get included even when added to asset.

**Comment by maxpavlov** [comment]
I have it with wrtc.node file which is seen as a part of the snapshot with DEBUG_PKG=1, yet the executable is still unable to find it as it looks in '/var/folders/' and not in a snapshot folder.
