### ISSUE TITLE
Spawn Child process of same application

### ISSUE THREAD

**Issue by sartaj-singh** [vercel/pkg#1292]
Tested Ubuntu:- I found a problem When i try to run one more app instance with child process spawn then it is failed to load module. But it is working fine on Windows 7 and 10 but failed on linux. When i checked the reason then i found environment variable was already set PKG_EXECPATH=/home/sartaj/www/res/sphpserver/sphpserver-linux. The child process load and run correctly if this variable is unset. You can see terminal output:-  /home/sartaj/www/res/sphpserver/sphpserver-linux --proj /home/sartaj/www/demo --port 8001
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/sartaj/www/res/sphpserver/--proj'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1711:46)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1739:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Problem:- it couldn't load start script correctly from internal path when  PKG_EXECPATH is set. Application work like as nodejs executable and find script path from hard disk.

**Comment by sartaj-singh** [comment]
I am resolved this problem by temporary solution with give the entry point.
