### ISSUE TITLE
MODULE_NOT_FOUND when running the executable after deleting node_modules folder

### ISSUE THREAD

**Issue by alimehasin** [vercel/pkg#1318]
When I am compile my typescript project and run the server.js it works fine and when I package it it also works fine but when I delete node_modules it throw **MODULE_NOT_FOUND** error which means that the executable make imports to the node_modules, looking at the first import caused the problem `__importDefault(require("bcrypt"));`

## tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "resolveJsonModule": true,
    "allowJs": false,
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

Env:
pkg version: 5.3.2
typescript version: 4.4.3

<details>
  <summary>Error log</summary>

```
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: Cannot find module '/snapshot/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
Require stack:
- /snapshot/app/node_modules/bcrypt/bcrypt.js
- /snapshot/app/dist/src/users/controller.js
- /snapshot/app/dist/src/users/router.js
- /snapshot/app/dist/src/users/index.js
- /snapshot/app/dist/src/routers.js
- /snapshot/app/dist/src/app.js
- /snapshot/app/dist/src/server.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1776:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/snapshot/app/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/app/node_modules/bcrypt/bcrypt.js',
    '/snapshot/app/dist/src/users/controller.js',
    '/snapshot/app/dist/src/users/router.js',
    '/snapshot/app/dist/src/users/index.js',
    '/snapshot/app/dist/src/routers.js',
    '/snapshot/app/dist/src/app.js',
    '/snapshot/app/dist/src/server.js'
  ],
  pkg: true
}
```  
</details>

**Comment by alimehasin** [comment]
@Kenhuey unfortunately, I haven't

**Comment by ChrisLincoln** [comment]
I stumbled upon pkg while looking for a solution to the very same problem when using wepback to bundle an app that uses bcrypt.  bcrypt has dependencies an at least one library a hard requirement for the existence of /node_modules/.

**Comment by valdastr** [comment]
Hi,

Might be not a correct way, but one can bundle the assets via `package.json` (see the Assets sections in docs):

`    "pkg": {
        "assets": [
            "node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node"
        ]
    }
`

**Comment by alimehasin** [comment]
Thanks @valdastr
