### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by praveenydv** [vercel/pkg#1328]
I created executable application using "pkg".
My application is running perfectly using node. But after creating executable application using "pkg", I am getting this error:

```
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/build/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/build/Debug/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/build/Release/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/out/Debug/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/Debug/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/out/Release/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/Release/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/build/default/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/compiled/14.17.2/linux/x64/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/addon-build/release/install-root/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/addon-build/debug/install-root/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/addon-build/default/install-root/node-librdkafka.node
 → /snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/lib/binding/node-v83-linux-x64/node-librdkafka.node
    at bindings (/snapshot/datoms_iot_hub_tcp_server/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/lib/client.js:14:13) {
  tries: [
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/build/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/build/Debug/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/build/Release/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/out/Debug/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/Debug/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/out/Release/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/Release/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/build/default/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/compiled/14.17.2/linux/x64/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/addon-build/release/install-root/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/addon-build/debug/install-root/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/addon-build/default/install-root/node-librdkafka.node',
    '/snapshot/datoms_iot_hub_tcp_server/node_modules/node-rdkafka/lib/binding/node-v83-linux-x64/node-librdkafka.node'
  ]
}

```

**Comment by robertsLando** [comment]
Should be fixed on master, wait for next release

**Comment by praveenydv** [comment]
Can you tell the expected time. When the next release will be published? So that I can manage things according to that.

**Comment by robertsLando** [comment]
Did you added `/node_modules/node-rdkafka/**` to your assets in package.json?

**Comment by robertsLando** [comment]
"/node_modules/node-rdkafka/**", should be "./node_modules/node-rdkafka/**",

**Comment by praveenydv** [comment]
I think assets command is not available in pkg-API. As only these commands are available in library
```
    string: [
      '_',
      'c',
      'config',
      'o',
      'options',
      'output',
      'outdir',
      'out-dir',
      'out-path',
      'public-packages',
      't',
      'target',
      'targets',
      'C',
      'compress',
    ],
```

**Comment by praveenydv** [comment]
thanks for your help
