### ISSUE TITLE
pkg my NodeProject find a problem

### ISSUE THREAD

**Issue by heyang-hy** [vercel/pkg#1335]
G:\Desktop\hidpos2wm>HidPos.exe
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

TypeError: Cannot read property '1' of null
    at process.dlopen (pkg/prelude/bootstrap.js:2071:69)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at bindings (C:\snapshot\hidpos2wm\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\snapshot\hidpos2wm\node_modules\@serialport\bindings\lib\win32.js:1:98)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)

**Comment by mregiste** [comment]
Same issue:

D:\rcon\usb_detect>usb_detect-node10-win.exe
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

TypeError: Cannot read property '1' of null
    at process.dlopen (pkg/prelude/bootstrap.js:2071:69)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (C:\snapshot\usb_detect\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\snapshot\usb_detect\node_modules\usb-detection\index.js:13:37)
