### ISSUE TITLE
Error: Cannot find module '/snapshot/app/node_modules/consign/locale/en-us'

### ISSUE THREAD

**Issue by AmeliaPessoa** [vercel/pkg#1347]
When I build the executable everything seems right but when I try to execute the file I have this error:

```
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: Cannot find module '/snapshot/app/node_modules/consign/locale/en-us'
Require stack:
- /snapshot/app/node_modules/consign/lib/consign.js
- /snapshot/app/node_modules/consign/index.js
- /snapshot/app/config/custom.js
- /snapshot/app/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:94:18)
    at new Consign (/snapshot/app/node_modules/consign/lib/consign.js)
    at /snapshot/app/node_modules/consign/lib/consign.js
    at /snapshot/app/config/custom.js
    at Object.<anonymous> (/snapshot/app/index.js) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/app/node_modules/consign/lib/consign.js',
    '/snapshot/app/node_modules/consign/index.js',
    '/snapshot/app/config/custom.js',
    '/snapshot/app/index.js'
  ]
}
```

I am using pkg 5.3.3 and consign 0.1.6.

I already tried to put this file on pkg assets on package.json file but I have no success:
```
"pkg": {
    "assets": [
      "node_modules/consign/**/*"
    ]
  }
``` 

Thanks for your help!

**Comment by Daniel-Olivier** [comment]
`node_modules/consign/locale/en-us` is a JSON file not a JavaScript file which may be causing some kind of weird edge case issue with require.resolve

Please try adding `require('node_modules/consign/locale/en-us.json')` somewhere in your code which will make sure pkg includes it in the built binary

You can also try logging `require.resolve('node_modules/consign/locale/en-us')` and `require.resolve('node_modules/consign/locale/en-us.json')` to debug the issue

**Comment by thePaulBurger** [comment]
@Daniel-Olivier Great reply. Solved my issue. Thanks
