### ISSUE TITLE
Incorrect behaviour when calling childProcess.fork with execArgv options

### ISSUE THREAD

**Issue by SBell6hf** [vercel/pkg#1438]
### What version of pkg are you using?

5.5.1

### What version of Node.js are you using?

16.13.0

### What operating system are you using?

macOS Monterey Version 12.0.1 (21A559)

### What CPU architecture are you using?

ARM64 (Apple M1)

### What Node versions, OSs and CPU architectures are you building for?

node14-macos-arm64

### Describe the Bug

`childProcess.fork()` throws an error when it's called with an execArgv option, for example, `--nolazy`.
It seems it's looking for a module named `--nolazy.js`.

### Expected Behavior

It works normally, just like when using `node XXX.js`.

### To Reproduce

```
$ npm i pkg
$ cat >a.js << END
let childProcess = require("child_process");
childProcess.fork("./b.js", [], {
	execArgv: ["--nolazy"]
});
END
$ cat >b.js << END
console.log("Hello.");
END
$ npx pkg -t node14-macos-arm64 a.js -o a
> pkg@5.5.1
$ ./a
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '(current work directory)/--nolazy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by SBell6hf** [comment]
May be fixed by: PR https://github.com/vercel/pkg/pull/1157

**Comment by SBell6hf** [comment]
​
