### ISSUE TITLE
Compressed server app fails to load TEMP files as those are not being generated to C:\Windows\TEMP

### ISSUE THREAD

**Issue by ingles98** [vercel/pkg#1439]
For some reason when I run my application's back-end through a GZip compressed PKG bundled file it works fine initially.

After connecting a client app to it that shouldn't actually run any filesystem stuff, the back-end stops responding to static requests (API still works fine).

I always seem to get the same error:

```
UncaughtException Error: ENOENT: no such file or directory, open 'C:\WINDOWS\TEMP\pkg-urWMOv\62b442e2f8a921bc366d5f2f43f9facdae4b578348da6c912dcba9ea6dcf745b'
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:739:32)
    at uncompressExternallyAndOpen (pkg/prelude/bootstrap.js:693:19)
    at pkg/prelude/bootstrap.js:709:32
    at FSReqCallback.oncomplete (node:fs:188:23) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\WINDOWS\\TEMP\\pkg-urWMOv\\62b442e2f8a921bc366d5f2f43f9facdae4b578348da6c912dcba9ea6dcf745b',
  level: 'info',
  [Symbol(level)]: 'info',
  [Symbol(message)]: "[Mon, 13 Dec 2021 15:34:30 GMT] info: ENOENT: no such file or directory, open 'C:\\WINDOWS\\TEMP\\pkg-urWMOv\\62b442e2f8a921bc366d5f2f43f9facdae4b578348da6c912dcba9ea6dcf745b'"
}
```

EDIT 1:  It seems it works fine by directly running in a console, however it fails if I run it through my WINSW wrapper (running as a Windows service). This however only happens with compression.

EDIT 2: It also seems that if i run the service with a user logon the problems is fixed, which is quite weird.

Edit 3: It fails to load something that is generated by PKG itself during runtime - When running in service with local service account it should be generating to `C:\Windos\TEMP` where it is actually attempting to open said generated file. However the directory (`pkg-urWMOv`) is not even being generated while if running on user account it is generated on Local\Temp without issues. Could be an issue with write permissions on this folder? Quite weird as services should be able to write to this directory when running as system account without issue...

**Comment by ingles98** [comment]
I cannot even get to know where to start from as the require stack is very minimal...
