### ISSUE TITLE
An error occurred when using pkg to package the playwright program

### ISSUE THREAD

**Issue by yizhiyan** [vercel/pkg#1445]
### What version of pkg are you using?

5.5.1

### What version of Node.js are you using?

v16.13.1

### What operating system are you using?

windows10

### What CPU architecture are you using?

x64

### What Node versions, OSs and CPU architectures are you building for?

node12

### Describe the Bug

I also encountered this problem when using pkg packaging
```
(function (exports, require, module, __filename, __dirname) { �PNG


SyntaxError: Invalid or unexpected token
    at new Script (vm.js:89:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
C:\snapshot\citi-reg\node_modules\playwright-core\lib\server\chromium\appIcon.png:1
(function (exports, require, module, __filename, __dirname) { �PNG


SyntaxError: Invalid or unexpected token
    at new Script (vm.js:89:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
> Warning Failed to make bytecode node12-x64 for file C:\snapshot\citi-reg\node_modules\playwright-core\lib\server\chromium\appIcon.png
```

### Expected Behavior

Packing without errors

### To Reproduce

When using playwright, this error will appear as long as the package is

**Comment by robertsLando** [comment]
@yizhiyan Seems you have included a png file as a script, it should be included as an asset
