### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by suntong** [vercel/pkg#1535]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-linux

### Describe the Bug

Same as https://github.com/vercel/pkg/issues/1328, which seems to be only fixable via new release:

```
(node:3043937) UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file. Tried:
 → /snapshot/src/node_modules/better-sqlite3/build/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/compiled/14.18.3/linux/x64/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /snapshot/src/node_modules/better-sqlite3/lib/binding/node-v83-linux-x64/better_sqlite3.node
    at bindings (/snapshot/src/node_modules/bindings/bindings.js:126:9)
    at new Database (/snapshot/src/node_modules/better-sqlite3/lib/database.js:48:64)
    at FlashStore.initSqlite (/snapshot/src/node_modules/flash-store/dist/src/flash-store.js:81:20)
    at new FlashStore (/snapshot/src/node_modules/flash-store/dist/src/flash-store.js:77:33)
    at CacheManager.init (/snapshot/src/node_modules/wechaty-puppet-padlocal/dist/padlocal/cache-manager.js:43:30)
```

### Expected Behavior

run should be successful.

### To Reproduce

I've provided a 2-file example:

- `git clone https://gist.github.com/suntong/14a3427a72c7023ef1c5148bd1be6d9a.git`
- `npm install`
- `pkg .`

**Comment by suntong** [comment]
added `node_modules/better-sqlite3/build/Release/*` to assets in package.json fixed the issue.

**Comment by daanlenaerts** [comment]
Thank you for the pointer @suntong. This did solve the issue for me as well. I'd like to add some clarifications though, for other people encountering this issue.

The assets should be added to your package.json file like this:
```json
{
  "name": "your-package-name",
  "version": "1.0.0",
  ...
  "pkg": {
    "assets": [
      "node_modules/better-sqlite3/build/Release/*"
    ]
  }
  ...
}
```

When running pkg, add a `--config` flag to indicate pkg should use the configuration defined in your package.json file. Like this:
```
pkg app.js --config package.json
```
