### ISSUE TITLE
pkg with worker_thread does not work

### ISSUE THREAD

**Issue by knifedog** [vercel/pkg#1546]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.14.0 LTS

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-win-x64 & node16-linux-x64

### Describe the Bug

user-defined worker-thread.js  file does not pack into the executable file

### Expected Behavior

All js file will pack into the exe file

### To Reproduce

code:
```javascript
const {
    Worker, isMainThread, parentPort, SHARE_ENV
} = require('worker_threads');
const mongoInit = require("./src/mongo-init.js");


//load .env file
require('dotenv').config();
const mongoURL = process.env.MONGO_URL;
const dbName = process.env.DB_NAME;
const configCollectionName = process.env.CONFIG_COLLECTION_NAME;

var workerList = [];


async function main() {
    result = await mongoInit(mongoURL, dbName, configCollectionName);
    for (let i = 0; i < result.length; i++) {
        console.log(result[i]);
        switch (result[i].Rule) {
            case "HWP":
                HWP_Worker(result[i]);
        }
    }
}

function HWP_Worker(data) {
    const worker = new Worker('./src/hwp-worker.js', {
        env: SHARE_ENV,
        workerData: data,
    });

    workerList.push(worker);
    worker.postMessage("hi");
    worker.on('message', (data) => {
        console.log(data);
    });
    worker.on('error', (err) => {
        console.log(err);
        worker.terminate();
    });
    worker.on('exit', (code) => {
        if (code !== 0)
            console.log(code);
    })
}

if (process.platform === "win32") {
    var rl = require("readline").createInterface({
        input: process.stdin,
        output: process.stdout
    });

    rl.on("SIGINT", function () {
        process.emit("SIGINT");
    });
}

process.on('SIGINT', function () {
    console.log("Caught interrupt signal");
    for (let i = 0; i < workerList.length; i++) {
        workerList[i].unref();
    }
    process.exit();
});

main();
```

error when executed:
```
Error: Cannot find module '/mnt/d/linux_workspace/nodejs_workspace/HWP/dist/src/hwp-worker.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:187:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I think pkg does not identify the code here:
```javascript
function HWP_Worker(data) {
    const worker = new Worker('./src/hwp-worker.js', {
        env: SHARE_ENV,
        workerData: data,
    });

    workerList.push(worker);
    worker.postMessage("hi");
    worker.on('message', (data) => {
        console.log(data);
    });
    worker.on('error', (err) => {
        console.log(err);
        worker.terminate();
    });
    worker.on('exit', (code) => {
        if (code !== 0)
            console.log(code);
    })
}
```
How can I solve it or any other ideas🙏

**Comment by knifedog** [comment]
Oh , I find my mistake , it's work now with:
```JSON
"pkg": {
    "scripts": "src/hwp-worker.js",
    "targets": [
      "node16-win-x64",
      "node16-linux-x64"
    ],
    "outputPath": "dist"
  }
```

the "scripts" field I wrote before:
```json
{"scripts" : "./src/hwp-worker.js"}
{"scripts" : "./src/*.js"}
```

**Comment by knifedog** [comment]
I find some problems when executed
```bash
node ./dist/mlc-hwp-linux  //in project root folder , it's work
node ./mlc-hwp-linux   //but in dist folder , it does not work
```

error code is same as above:
```
Error: Cannot find module '/mnt/d/linux_workspace/nodejs_workspace/MLC_HWP/dist/src/hwp-worker.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:187:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by xts-bit** [comment]
@knifedog Did you fix ?
