### ISSUE TITLE
Executable broken when called with `PKG_EXECPATH` set to its own absolute path

### ISSUE THREAD

**Issue by 0x2b3bfa0** [vercel/pkg#1565]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.14.0

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-linux-x64

### Describe the Bug

Calling an executable created with `pkg` with the `PKG_EXECPATH` environment variable set to the absolute path of the executable produces an error.

### Expected Behavior

Setting the `PKG_EXECPATH` environment variable to the absolute path of the executable should not produce any error:

```console
$ tee test.js <<< "console.log('test');"
console.log('test');
$ pkg test.js --target=node16-linux-x64 --output=test
pkg@5.5.2
$ ./test
test
$ PKG_EXECPATH=$(realpath test) ./test
test
$ PKG_EXECPATH=$(realpath test) ./test argument
test
```

### To Reproduce

Setting the `PKG_EXECPATH` environment variable to the absolute path of the executable produces an error:

```console
$ tee test.js <<< "console.log('test');"
console.log('test');
$ pkg test.js --target=node16-linux-x64 --output=test
pkg@5.5.2
$ ./test
test
$ PKG_EXECPATH=$(realpath test) ./test
pkg/prelude/bootstrap.js:1813
      if (error.code !== 'MODULE_NOT_FOUND') throw error;
                                             ^
TypeError: String.prototype.startsWith called on null or undefined
    at startsWith (<anonymous>)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:849:7)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1811:44)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)
    at node:internal/main/run_main_module:17:47
$ PKG_EXECPATH=$(realpath test) ./test argument
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module '/path/to/current/directory/argument'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by 0x2b3bfa0** [comment]
https://github.com/vercel/pkg/blob/2ef4cd95371ec81545069ba3541423332b09fd14/prelude/bootstrap.js#L77-L89

#### `TypeError: String.prototype.startsWith called on null or undefined`

* Condition at line 77 is `true` (executable called with `PKG_EXECPATH` set to its own absolute path)
* Condition at line 80 is `false` (executable called without arguments, or the first argument is a hyphen)
* Value of `process.argv[1]` remains `undefined` because no other assignment is being made
* Value of `ENTRYPOINT` becomes `process.argv[1]` at line 88

#### `Error: Cannot find module '/path/to/current/directory/argument'`

* Condition at line 77 is `true` (executable called with `PKG_EXECPATH` set to its own absolute path)
* Condition at line 80 is `true` (executable called with one or more arguments, and the first argument isn't a hyphen)
* Value of `process.argv[1]` becomes `path.resolve(process.argv[1])`[^1] 
* Value of `ENTRYPOINT` becomes `process.argv[1]` at line 88

https://github.com/vercel/pkg/blob/2ef4cd95371ec81545069ba3541423332b09fd14/prelude/bootstrap.js#L1846

Value of `ENTRYPOINT` (either `undefined` or a non–existent path) is used to call the `_load` function, producing an error.

[^1]: Namely, `'/path/to/current/directory/argument'`

**Comment by 0x2b3bfa0** [comment]
https://github.com/vercel/pkg/blob/2ef4cd95371ec81545069ba3541423332b09fd14/prelude/bootstrap.js#L77-L89

#### `TypeError: String.prototype.startsWith called on null or undefined`

* Condition at line 77 is `true` (executable called with `PKG_EXECPATH` set to its own absolute path)
* Condition at line 80 is `false` (executable called without arguments, or the first argument is a hyphen)
* Value of `process.argv[1]` remains `undefined` because no other assignment is being made
* Value of `ENTRYPOINT` becomes `process.argv[1]` at line 88

#### `Error: Cannot find module '/path/to/current/directory/argument'`

* Condition at line 77 is `true` (executable called with `PKG_EXECPATH` set to its own absolute path)
* Condition at line 80 is `true` (executable called with one or more arguments, and the first argument isn't a hyphen)
* Value of `process.argv[1]` becomes `path.resolve(process.argv[1])`[^1] 
* Value of `ENTRYPOINT` becomes `process.argv[1]` at line 88

https://github.com/vercel/pkg/blob/2ef4cd95371ec81545069ba3541423332b09fd14/prelude/bootstrap.js#L1846

Value of `ENTRYPOINT` (either `undefined` or a non–existent path) is used to call the `_load` function, producing an error.

[^1]: Namely, `'/path/to/current/directory/argument'`

**Comment by 0x2b3bfa0** [comment]
It turns out that there aren't other solutions apart from unsetting `PKG_EXECPATH` as proposed on #897. At least, I haven't found any.
