### ISSUE TITLE
dynamic execute a js file

### ISSUE THREAD

**Issue by yuql** [vercel/pkg#1573]
**What version of pkg are you using?**
5.5.2

**What version of Node.js are you using?**
16.14.2

**What operating system are you using?**
windows10

**What CPU architecture are you using?**
x86_64

**What Node versions, OSs and CPU architectures are you building for?**
win

**Describe the Bug**

I build a .exe file, and it work well~~
in the .exe , I dynamic require a outside js file(no need packed int .exe, it dynamic generate by other program , example: a.js or b.js or xxx.js), in the js file also require some module like lodash, 
but when run the js file function ,it tell me :

  Error: Cannot find module 'lodash'
  Require stack:
  - C:\Users\Administrator\Desktop\1_1.0.0.js
  - C:\snapshot\xxx\services\other.js
  - C:\snapshot\xxx\services\some.js
  - C:\snapshot\xxx\main.js
  1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at Module.require (pkg/prelude/bootstrap.js:1719:31)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (C:\Users\Administrator\Desktop\1_1.0.0.js:5:18)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Module._compile (pkg/prelude/bootstrap.js:1758:32)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\Administrator\\Desktop\\1_1.0.0.js',
      'C:\\snapshot\\xxx\\services\\other.js',
      'C:\\snapshot\\xxx\\services\\some.js',
      'C:\\snapshot\\xxx\\main.js'
    ],
    pkg: true
  }
]

**Comment by yuql** [comment]
in 1_1.0.0.js , I use require(process.cwd() + '/node_modules/lodash');
it error with : 
Error: Cannot find module 'C:\Users\Administrator\Desktop/node_modules/lodash'
