### ISSUE TITLE
extract absolute snapshot paths ENOENT

### ISSUE THREAD

**Issue by alex-Symbroson** [vercel/pkg#1583]
### What version of pkg are you using?

5.1.0

### What version of Node.js are you using?

16.10.0

### What operating system are you using?

Ubuntu 20.04.4 LTS

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

linux-x64

### Describe the Bug

I'm trying to extract assets from the snapshot tothe users filesystem.
when copying relative file path it works just fine
but when using absolute paths which are resolved to "/snapshot/pkgex/..." copyFile trows an ENOENT

### Expected Behavior

no error when copying absolute snapshot paths

### To Reproduce

```js
const fs = require('fs');
const path = require('path');
const os = require('os');

var src = /*/path.basename/**/(__filename);
var dst = path.join(os.homedir(), "worked");

fs.copyFileSync(src, dst);
```
output
```
Error: ENOENT: no such file or directory, copyfile '/snapshot/pkgex/index.js' -> '/home/symbroson/worked'
    at Object.copyFileSync (node:fs:2085:3)
    at Object.<anonymous> (/snapshot/pkgex/index.js:9:8)
    at Module._compile (pkg/prelude/bootstrap.js:1503:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1558:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/snapshot/pkgex/index.js',
  dest: '/home/symbroson/worked'
}
```

with path.basename enabled it works

**Comment by robertsLando** [comment]
@alex-Symbroson Are you sure you are using latest pkg version? That patch is available starting from 5.6.0
