### ISSUE TITLE
Dynamic loading not supported ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by axi92** [vercel/pkg#1608]
### What version of pkg are you using?

5.6.0

### What version of Node.js are you using?

14.19.1

### What operating system are you using?

container node:14.19.1-bullseye and node:16.15.0-bullseye

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-linuxstatic-x64

### Describe the Bug

When I start my program with or without DEBUG_PKG=1 I get always this.

```
pkg/prelude/bootstrap.js:1833
      throw error;
      ^

Error: Dynamic loading not supported
    at process.dlopen (pkg/prelude/bootstrap.js:2212:28)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1812:31)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/snapshot/root/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

I tried to uprade the bluetooth-hci-socket packat to the latest git master commit because there was a rework with an relative path to a node binding. https://github.com/abandonware/node-bluetooth-hci-socket/blob/master/lib/native.js#L2 But that does not fix the problem.
```
pkg/prelude/bootstrap.js:1833
      throw error;
      ^

Error: Dynamic loading not supported
    at process.dlopen (pkg/prelude/bootstrap.js:2212:28)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1812:31)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/snapshot/root/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:2:30)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Those are my assets:
```
    "assets": [
      "node_modules/@serialport/bindings/build/Release/bindings.node",
      "node_modules/@abandonware/bluetooth-hci-socket/lib/binding/*",
      "node_modules/@abandonware/noble/build/Release/noble.node",
      "node_modules/node-hid/build/Release/HID_hidraw.node",
      "node_modules/node-hid/build/Release/HID.node",
      "node_modules/usb/prebuilds/linux-x64/node.napi.glibc.node",
      "node_modules/usb/prebuilds/linux-arm64/node.napi.armv8.node",
      "node_modules/usb/package.json",
      "package.json",
      "node_modules/@abandonware/bluetooth-hci-socket/build/Release/bluetooth_hci_socket.node"
    ]
```

Any Ideas?

With pkg debug I get this at the end, but the files are there.
```
> [debug] prebuild-install failed[/home/user/Workspace/git/nwp-pi-bridge/node_modules/@serialport/bindings/build/Release/bindings.node]:
  spawnSync /home/user/Workspace/git/nwp-pi-bridge/node_modules/pkg/node_modules/.bin/prebuild-install ENOENT
> [debug] prebuild-install failed[/home/user/Workspace/git/nwp-pi-bridge/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node]:
  spawnSync /home/user/Workspace/git/nwp-pi-bridge/node_modules/pkg/node_modules/.bin/prebuild-install ENOENT
> [debug] prebuild-install failed[/home/user/Workspace/git/nwp-pi-bridge/node_modules/@abandonware/bluetooth-hci-socket/build/Release/bluetooth_hci_socket.node]:
  spawnSync /home/user/Workspace/git/nwp-pi-bridge/node_modules/pkg/node_modules/.bin/prebuild-install ENOENT
> [debug] prebuild-install failed[/home/user/Workspace/git/nwp-pi-bridge/node_modules/@abandonware/noble/build/Release/noble.node]:
  spawnSync /home/user/Workspace/git/nwp-pi-bridge/node_modules/pkg/node_modules/.bin/prebuild-install ENOENT
> [debug] prebuild-install failed[/home/user/Workspace/git/nwp-pi-bridge/node_modules/node-hid/build/Release/HID_hidraw.node]:
  spawnSync /home/user/Workspace/git/nwp-pi-bridge/node_modules/pkg/node_modules/.bin/prebuild-install ENOENT
> [debug] prebuild-install failed[/home/user/Workspace/git/nwp-pi-bridge/node_modules/node-hid/build/Release/HID.node]:
  spawnSync /home/user/Workspace/git/nwp-pi-bridge/node_modules/pkg/node_modules/.bin/prebuild-install ENOENT
> [debug] prebuild-install failed[/home/user/Workspace/git/nwp-pi-bridge/node_modules/usb/prebuilds/linux-x64/node.napi.glibc.node]:
  spawnSync /home/user/Workspace/git/nwp-pi-bridge/node_modules/pkg/node_modules/.bin/prebuild-install ENOENT
> [debug] prebuild-install failed[/home/user/Workspace/git/nwp-pi-bridge/node_modules/usb/prebuilds/linux-arm64/node.napi.armv8.node]:
  spawnSync /home/user/Workspace/git/nwp-pi-bridge/node_modules/pkg/node_modules/.bin/prebuild-install ENOENT
```

### Expected Behavior

I would expect that the binding is found in pkg.

### To Reproduce

I have to make an example to test...

**Comment by axi92** [comment]
Ok it looks like node14-linuxstatic-x64 is not working, with bindings only dynamic is supported I guess.
"node14-linux-x64"
