### ISSUE TITLE
Executable containing other binaries will fail to start if temp are partially cleaned

### ISSUE THREAD

**Issue by TsFreddie** [vercel/pkg#1622]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.14.2

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16

### Describe the Bug

I used pkg to package swc which worked flawlessly until either Windows or other tools cleaned out the binary from `%LOCALAPPDATA%/Temp/pkg`

More specifically, the files under the path `%TEMP%/pkg/<hash>/core-win32-x64-msvc` was cleaned, but the folder itself still exists as an empty folder.

LOG:

```
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: The specified module could not be found.
C:\Users\<removed>\AppData\Local\Temp\pkg\c55df18b3e489ac79434e4a02dfe6fa1e25d3d463ee68c3bbfcc7691fe293a64\@swc\core-win32-x64-msvc\swc.win32-x64-msvc.node
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\snapshot\compiler\node_modules\@swc\core\binding.js:67:41)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

### Expected Behavior

The app should start normally.

### To Reproduce

1. Create a empty project
2. Install and import `@swc/core`
3. Build
4. Run the executable once
5. Delete files under `%TEMP%/pkg/<hash>/core-win32-x64-msvc` but not the folder itself
6. Run the executable again

**Comment by robertsLando** [comment]
Should be fixed by https://github.com/vercel/pkg/pull/1611
