### ISSUE TITLE
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value: (0, assert_1.default)(!this.bar)

### ISSUE THREAD

**Issue by Leoff00** [vercel/pkg#1631]
### What version of pkg are you using?

5.6.0

### What version of Node.js are you using?

16.13.2

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-win-arm64

### Describe the Bug

The stacktrace show that i can't generate a bin file because it shows that have a syntax error in the file **lib-es5** into the folder pkg-fetch inside the node_modules globally.

Here's the stacktrace: 

pkg@5.6.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.19.1-win-arm64          [                    ] 0%> Not found in remote cache:
  {"tag":"v3.3","name":"node-v14.19.1-win-arm64"}
> Building base binary from source:
  built-v14.19.1-win-arm64
> Fetching Node.js source archive from nodejs.org...
> Error! AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(!this.bar)

    at Log.enableProgress (C:\Users\leolu\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\log.js:64:30)
    at C:\Users\leolu\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:58:31
    at step (C:\Users\leolu\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:33:23)
    at Object.next (C:\Users\leolu\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:14:53)
    at C:\Users\leolu\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\leolu\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:4:12)
    at downloadUrl (C:\Users\leolu\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:53:12)
    at C:\Users\leolu\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js:140:66
    at step (C:\Users\leolu\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js:44:23)

### Expected Behavior

Generate the executable file in the root directory

### To Reproduce

```pkg -t node14-win-arm64 dist/src/server.js```

**Comment by robertsLando** [comment]
Try with latest 5.7.0 version

**Comment by DarkCWK** [comment]
> It works, for some reason this bug happens when i do install the **pkg** locally. I setted the **pkg** env variables on windows and run the command globally and works.

How did you solve it? I also have this problem. But I am using the latest version.

**Comment by Leoff00** [comment]
There isn't a new version of **pkg** for newest node versions, i had to work with PKG in the node v16 and solve the problem

**Comment by pvx-aidan** [comment]
I had the same issue that ended up being caused by my companies proxy (MITM SSL decryption)

**Comment by ohhoney1** [comment]
try download it by yourself，in https://github.com/vercel/pkg-fetch/releases, and rename 'node14-win-arm64' to 'fetched-v14.19.1-win-arm64'.

**Comment by aviTwito** [comment]
> try download it by yourself，in https://github.com/vercel/pkg-fetch/releases, and rename 'node14-win-arm64' to 'fetched-v14.19.1-win-arm64'.

Can you share more info? I got the same problem. I tried downloaing node-v16.16.0-win-x64 and ran ``` pkg -t fetched-v16.15.0-win-x64 main.js```

output: 
```
> pkg@5.8.0
> Error! Unknown token 'fetched' in 'fetched-v16.15.0-win-x64'
```

**Comment by aviTwito** [comment]
> There isn't a new version of **pkg** for newest node versions, i had to work with PKG in the node v16 and solve the problem



> It works, for some reason this bug happens when i do install the **pkg** locally. I setted the **pkg** env variables on windows and run the command globally and works.

I`m having the exact same issue:
```
pkg -t node16-win-x64 main.js
> pkg@5.8.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v16.16.0-win-x64            [                    ] 0%> Not found in remote cache:
  {"tag":"v3.4","name":"node-v16.16.0-win-x64"}
> Building base binary from source:
  built-v16.16.0-win-x64
> Fetching Node.js source archive from nodejs.org...
> Error! AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(!this.bar)

    at Log.enableProgress (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\log.js:64:30)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:58:31
    at step (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:33:23)
    at Object.next (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:14:53)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:4:12)
    at downloadUrl (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:53:12)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js:142:66
    at step (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js:44:23)
```


What env variables did you configured and how?

**Comment by ohhoney1** [comment]
> > try download it by yourself，in https://github.com/vercel/pkg-fetch/releases, and rename 'node14-win-arm64' to 'fetched-v14.19.1-win-arm64'.
> 
> Can you share more info? I got the same problem. I tried downloaing node-v16.16.0-win-x64 and ran ` pkg -t fetched-v16.15.0-win-x64 main.js`
> 
> output:
> 
> ```
> > pkg@5.8.0
> > Error! Unknown token 'fetched' in 'fetched-v16.15.0-win-x64'
> ```

after downloaded and renamed, have a try:  `pkg -t node-v16.16.0-win-x64 main.js`

**Comment by Leoff00** [comment]
> > There isn't a new version of **pkg** for newest node versions, i had to work with PKG in the node v16 and solve the problem
> 
> > It works, for some reason this bug happens when i do install the **pkg** locally. I setted the **pkg** env variables on windows and run the command globally and works.
> 
> I`m having the exact same issue:
> 
> ```
> pkg -t node16-win-x64 main.js
> > pkg@5.8.0
> > Fetching base Node.js binaries to PKG_CACHE_PATH
>   fetched-v16.16.0-win-x64            [                    ] 0%> Not found in remote cache:
>   {"tag":"v3.4","name":"node-v16.16.0-win-x64"}
> > Building base binary from source:
>   built-v16.16.0-win-x64
> > Fetching Node.js source archive from nodejs.org...
> > Error! AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
> 
>   (0, assert_1.default)(!this.bar)
> 
>     at Log.enableProgress (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\log.js:64:30)
>     at C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:58:31
>     at step (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:33:23)
>     at Object.next (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:14:53)
>     at C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:4:12)
>     at downloadUrl (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:53:12)
>     at C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js:142:66
>     at step (C:\Users\xxx\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js:44:23)
> ```
> 
> What env variables did you configured and how?

I just installed the pkg globally, for some reason installing the **pkg** in your directory gives this error. Try to install the **pkg** lib with the flag -g to install globally, restart and try to run this command again.

**Comment by holema** [comment]
I have the same issue. running pkg in a docker container.
node v16.16.0
I installed it globaly with -g

**Comment by aviTwito** [comment]
Solved it by using [this explanation](https://segmentfault.com/a/1190000041958374/en)
