### ISSUE TITLE
Pkg giving error while using libc++ compiled node 

### ISSUE THREAD

**Issue by dashjuthika** [vercel/pkg#1726]
### What version of pkg are you using?

5.8

### What version of Node.js are you using?

16.16.0

### What operating system are you using?

Ubuntu

### What CPU architecture are you using?

x86

### What Node versions, OSs and CPU architectures are you building for?

ChromeOS

### Describe the Bug

I compiled Node with libc++ instead of libstdc++. But then pkg is incomputable with this version of node. Getting the below error:

        node:assert:399
            throw err;
            ^
        
        
        
        AssertionError [ERR_ASSERTION]: Placeholder for not found
            at injectPlaceholder (/usr/local/lib/node_modules/pkg/lib-es5/producer.js:29:30)
            at injectPlaceholders (/usr/local/lib/node_modules/pkg/lib-es5/producer.js:56:5)
            at /usr/local/lib/node_modules/pkg/lib-es5/producer.js:319:17
            at /usr/local/lib/node_modules/pkg/node_modules/graceful-fs/graceful-fs.js:362:16
            at FSReqCallback.oncomplete (node:fs:188:23) {
          generatedMessage: false,
          code: 'ERR_ASSERTION',
          actual: false,
          expected: true,
          operator: '=='
        }

### Expected Behavior

It should package

### To Reproduce

compile node with libc++ and use pkg to package any node project

**Comment by dashjuthika** [comment]
I am able to build  node with libc++
