### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Placeholder for not found

### ISSUE THREAD

**Issue by phr34k** [vercel/pkg#1806]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

18.12.0

### What operating system are you using?

windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node-16.16.0-win_x86, node-18.5.0-win_x86

### Describe the Bug

When I try to use pkg to compile a js file as a standalone executable, the target platform is x86 with visual studio 2022. I run into problems. Targetting node version 16.16.0 compiles the files but throws an assert after compilation. The 18.5.0 also throws the same assert, with the additional footnote that 18.5.0 will give you linker errors if you compile with the default selected build tools v143 (vs2022) - however forcing v142 (vs2019) works fine though.

The assert seems to happens in combination with compilation, it doesn't seem to happen when pkg-fetch bypasses compilation because it been able to find an prebuilt one from `pkg-fetch`. Unfortunately `pkg-fetch` only makes releases of x64 and in my situation I'm always building node from source. 
``` 
> pkg@5.8.0
node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Placeholder for not found
    at injectPlaceholder (C:\Users\phpfr\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:29:30)
    at injectPlaceholders (C:\Users\phpfr\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:56:5)
    at C:\Users\phpfr\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:319:17
    at C:\Users\phpfr\AppData\Roaming\npm\node_modules\pkg\node_modules\graceful-fs\graceful-fs.js:362:16
    at FSReqCallback.oncomplete (node:fs:201:23) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
````

```
     Creating library out\Release\node.lib and object out\Release\node.exp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 1638 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  node.vcxproj -> out\Release\\node.exe
The system cannot find the file specified.
Junction created for Release <<===>> out\Release
node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Placeholder for not found
    at injectPlaceholder (C:\Users\phpfr\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:29:30)
    at injectPlaceholders (C:\Users\phpfr\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:56:5)
    at C:\Users\phpfr\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:319:17
    at C:\Users\phpfr\AppData\Roaming\npm\node_modules\pkg\node_modules\graceful-fs\graceful-fs.js:362:16
    at FSReqCallback.oncomplete (node:fs:201:23) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v18.5.0
```

Would appreciate any insights to get this problem resolved.

### Expected Behavior

No errors

### To Reproduce

```
install visual studio 2022 - 17.4
install node 18.12.1.0 from nodejs website
npm -g i pgk@5.8.0
pkg -t node16.16-win-x86 somefile.js
SET msbuild_args=/p:PlatformToolset=v142
pkg -t node18.5-win-x86 server.js
````

### Extra

I set a couple of breakpoints and then discovered that the binary built by `pkg` didn't have any of the patched code applied. I suspected that maybe the patch wasn't applied because source code differences. When I run a debug build I discovered that when applying patches it's using an executable/script called 'patch'  from an unexpected area. 

```
> Applying patches
patching file common.gypi
Assertation failed!

Program: D:\SDK\Strawberry\c\bin\patch.exe
File: .\src\patch\2.5.9\patch-2.5.9-src\patch.c, Line 354
```

**Comment by phr34k** [comment]
When I added patch.exe from my git for windows installation it works as expected, and generates a patched binary. So the patch.exe that got bunddled from my old perl installation was causing and error. 

Admitedly these environment problem are beyond the scope of the library, but I do want to bring up that error handeling could be improved. Clearly the patches didn't apply, and aborting and clearly articulate on the reason would have been more informative rather than supressing the error and try to compile it unpatched.

```
GNU patch 2.7.6
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall
```
