### ISSUE TITLE
Missing stat.isBlockDevice and stat.isCharacterDevice for Snapshot fs

### ISSUE THREAD

**Issue by andriusvelykis** [vercel/pkg#1813]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

16.16.0

### What operating system are you using?

macOS

### What CPU architecture are you using?

Apple M1

### What Node versions, OSs and CPU architectures are you building for?

node16-macos-x64

### Describe the Bug

The implementation of Node `fs` that `pkg` uses for Snapshot filesystem is missing `stat.isBlockDevice` and `stat.isCharacterDevice` values when performing `fs.lstatSync`. This leads to errors in code that expects these fields to exist, e.g. like the popular [`fast-glob`](https://www.npmjs.com/package/fast-glob) package in the following code: https://github.com/mrmlnc/fast-glob/blob/a028e3670ba3186a102cb9108e3a6e48c1148a9e/src/utils/fs.ts#L15-L16 .

This omission has already been spotted by @sommd in an earlier `pkg` PR [#720](https://github.com/vercel/pkg/issues/720#issuecomment-508783499), suggesting to always return `false` in these cases. I imagine the implementation would be similar to `stat.isFIFO` in https://github.com/vercel/pkg/blob/e3ac4902e9cb023f0ac2a596e21ff9166d2e268c/prelude/bootstrap.js#L1434-L1436 ?

### Expected Behavior

`stat.isBlockDevice` and `stat.isCharacterDevice` defined when invoking `fs.lstatSync` (and similar) in Snapshot fs.

### To Reproduce

A reproduction involving `fast-glob` package to perform a glob-based lookup on a `pkg`-packaged executable is available in this repository: https://github.com/andriusvelykis/pkg-fast-glob-lstat-error .

A description of the issue reproduction is also provided below.

Consider an NPM package with the main file in `src/index.js`. An additional file `src/myfiles/hello.js` exists in the package. The contents of `src/index.js` are the following:

```javascript
const fg = require('fast-glob');
const path = require('path');

console.log("Current dir: " + __dirname);

const entries = fg.sync([path.join(__dirname, 'myfiles', 'hello.js')], { dot: true });

console.log("Packaged entries: " + entries.toString());
```

When running it directly, the globbing functionality works ok and the following message is output:

```
Current dir: /Users/myname/pkg-fast-glob-lstat-error/src
Packaged entries: /Users/myname/pkg-fast-glob-lstat-error/src/myfiles/hello.js
```

However, when the whole package is packaged via `pkg . --targets node16-macos-x64`, running the executable throws the following error:
```
Current dir: /snapshot/pkg-fast-glob-lstat-error/src
/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/readers/sync.js:36
            throw error;
            ^

TypeError: Cannot read properties of undefined (reading 'bind')
    at new DirentFromStats (/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/utils/fs.js:7:50)
    at Object.createDirentFromStats (/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/utils/fs.js:17:12)
    at ReaderSync._makeEntry (/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/readers/reader.js:22:30)
    at ReaderSync._getEntry (/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/readers/sync.js:30:25)
    at ReaderSync.static (/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/readers/sync.js:19:32)
    at ProviderSync.api (/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/providers/sync.js:20:29)
    at ProviderSync.read (/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/providers/sync.js:13:30)
    at Array.map (<anonymous>)
    at getWorks (/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/index.js:59:18)
    at AsyncFunction.sync (/snapshot/pkg-fast-glob-lstat-error/node_modules/fast-glob/out/index.js:20:23)
```

The above stack trace points to a failure in line 
```javascript
this.isBlockDevice = stats.isBlockDevice.bind(stats);
```

The error is thrown because the `pkg` `fs` implementation does not provide implementations of `stats.isBlockDevice` and `stats.isCharacterDevice` for the Snapshot file system.

**Comment by andriusvelykis** [comment]
The issue is still valid
