### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by Fosnos** [vercel/pkg#1814]
Node Version : `16.6`

Error Stack : 
```js
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 → C:\snapshot\Stealer\node_modules\win-dpapi\build\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\build\Debug\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\build\Release\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\out\Debug\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\Debug\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\out\Release\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\Release\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\build\default\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\compiled\16.16.0\win32\x64\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\addon-build\release\install-root\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\addon-build\debug\install-root\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\addon-build\default\install-root\node-dpapi.node
 → C:\snapshot\Stealer\node_modules\win-dpapi\lib\binding\node-v93-win32-x64\node-dpapi.node
    at bindings (C:\snapshot\Stealer\node_modules\[4mbindings[24m\bindings.js:126:9)
    at Object.<anonymous> (C:\snapshot\Stealer\node_modules\[4mwin-dpapi[24m\index.js:1:96)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:981:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)[39m
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
[90m    at require (node:internal/modules/cjs/helpers:102:18)[39m
    at Object.<anonymous> (C:\snapshot\Stealer\main.js) {
  tries: [
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\build\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\build\\Debug\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\build\\Release\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\out\\Debug\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\Debug\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\out\\Release\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\Release\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\build\\default\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\compiled\\16.16.0\\win32\\x64\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\addon-build\\release\\install-root\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\addon-build\\debug\\install-root\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\addon-build\\default\\install-root\\node-dpapi.node'[39m,
    [32m'C:\\snapshot\\Stealer\\node_modules\\win-dpapi\\lib\\binding\\node-v93-win32-x64\\node-dpapi.node'[39m
  ]
}
```

I Tried \`node-gyp rebuild\`, But Still It Showed Could Not Locate....

**Comment by robertsLando** [comment]
Add `node_modules\win-dpapi\` to assets

**Comment by Fosnos** [comment]
> vcbuild.bat
> Applying patches
> Error! Error: spawnSync patch ENOENT
    at Object.spawnSync (node:internal/child_process:1086:20)
    at spawnSync (node:child_process:812:24)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:148:51
    at step (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:33:23)
    at Object.next (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:14:53)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:4:12)
    at spawn (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:145:12)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js:221:60

**Comment by Fosnos** [comment]
im getting this error
