### ISSUE TITLE
Error! Error: spawnSync patch ENOENT

### ISSUE THREAD

**Issue by Fosnos** [vercel/pkg#1816]
```cmd
> vcbuild.bat
> Applying patches
> Error! Error: spawnSync patch ENOENT
    at Object.spawnSync (node:internal/child_process:1086:20)
    at spawnSync (node:child_process:812:24)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:148:51
    at step (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:33:23)
    at Object.next (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:14:53)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:4:12)
    at spawn (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\utils.js:145:12)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\build.js:221:60
```

**Comment by mirobo** [comment]
See https://github.com/vercel/pkg/issues/236#issuecomment-1014855851

> You must make the patch utility available in the PATH. It can usually be installed with the package manager of your distribution. On Windows, some tools such as Git Bash bundle this utility.
