### ISSUE TITLE
Package nextjs application fails on execution

### ISSUE THREAD

**Issue by pustekuchen91** [vercel/pkg#1823]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

18.12.1

### What operating system are you using?

linux mint

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node18-linux-x64, node18-win-x64

### Describe the Bug

Hello folks,

i'm trying to package a nextjs application. When executing the executable i'm getting this error, because `app.prepare()` throws an exception. Running the application just with node server.js does everything right.

```
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (/tmp/webpack:/my-project/node_modules/next/dist/lib/find-pages-dir.js:86:1)
    at new DevServer (/tmp/c5683c1b914babaffa2f5e21cba24fdf248dcd696470bfc113963db5a3792966/index.js:141975:59)
    at NextServer.createServer (/tmp/webpack:/my-project/node_modules/next/dist/server/next.js:140:1)
    at /tmp/webpack:/my-project/node_modules/next/dist/server/next.js:155:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NextServer.prepare (/tmp/webpack:/my-project/node_modules/next/dist/server/next.js:130:1)
Process exited with code: 0
```

Run with ``DEBUG_PKG=1` (Log is Reduced)

```
------------------------------- virtual file system
/snapshot
  my-project                             997203361 
    server.js                                 2375 
    package.json                              2773 
    next.config.js                             228 
    .next                                879496892 
      build-manifest.json                      874 
      package.json                              20 
      react-loadable-manifest.json               2 
      trace                                  24907 
      server                               3476275 
        middleware-build-manifest.js           694 
        middleware-react-loadable-manifest.js        33 
        webpack-api-runtime.js                6645 
        webpack-runtime.js                    9516 
        middleware-manifest.json                83 
        pages-manifest.json                    219 
        pages                              3450472 
          _app.js                          3187328 
          _document.js                      142493 
          _error.js                          51075 
          index.js                           18831 
          login.js                           19926 
          api                              3433282 
            auth                             13629 
              [...nextauth].js               13629 
      cache                              813435705 
         ...
      static                             879491516 
        chunks                            66043692 
          amp.js                           3769843 
          main.js                          4529104 
          polyfills.js                       91460 
          react-refresh.js                   78104 
          webpack.js                         47935 
          pages                           66043692 
            _app.js                       48911827 
            _error.js                         3392 
            index.js                         10272 
            login.js                       8601755 
        development                       66044135 
          _buildManifest.js                    367 
          _ssgManifest.js                       76 
        webpack                           66046283 
          webpack.5b66bceed71c0a42.hot-update.js      1228 
          webpack.d946977512637c34.hot-update.js       858 
          5b66bceed71c0a42.webpack.hot-update.json        31 
          d946977512637c34.webpack.hot-update.json        31 
        media                             66055811 
          xxx.0ede69e7.png      9528 
    node_modules                         997203361 
      bootstrap                            9087930 
        package.json                          9330 
        scss                                299294 
        ....
Total size =  909856093
```

### Expected Behavior

app.prepare() should succesful run within the executable.

### To Reproduce

server.js
```
const { createServer } = require('http')
const { parse } = require('url')
const next = require('next')
const nextConfig = require('./next.config')
const { dirname } = require('path')
require('dotenv').config()

const express = require('express');

const dev = process.env.NODE_ENV !== 'production' || false
const hostname = process.env.NODE_HOSTNAME || localhost
const port = parseInt(process.env.NODE_PORT) || 3001

// when using middleware `hostname` and `port` must be provided below
const app = next({ dev, dir: __dirname, conf: nextConfig })
//const app = next({ dev})
const handle = app.getRequestHandler()

process.on('exit', code => {
  // Only synchronous calls
  console.log(`Process exited with code: ${code}`)
})

app.prepare().then(() => {
  createServer((req, res) => {
    try {
      handle(req, res, parse(req.url, true).pathname)
    } catch (err) {
      console.log('Error occurred handling', req.url, err)
      console.error('Error occurred handling', req.url, err)
      res.statusCode = 500
      res.end('internal server error')
    }
  }).listen(port, (err) => {
    if (err) throw err
    console.log(`> Ready on http://${hostname}:${port}`)
  })
}).catch((e) => {
    console.log("Prepare failed: ")
    console.log(e)
})

```

**Comment by pustekuchen91** [comment]
I've done changes in the server.js `const app = next({ dev, conf: nextConfig })`, now i get the following errors..

```

info  - Loaded env from /workspaces/my-project/.env
error - ../../snapshot/my-project/node_modules/next/dist/client/dev/amp-dev.js
Error
wait  - compiling...
error - ../../snapshot/my-project/node_modules/next/dist/client/dev/amp-dev.js
Error
wait  - compiling...
error - ../../snapshot/my-project/node_modules/next/dist/pages/_document.js
Error
handle request
```

**Comment by danielrotaermel** [comment]
@pustekuchen91 did you figure it out by any chance? I tried so many things to get it working but it won't right now. I can package it without warnings but when I run it it fails to find the pages directory. Note: I am using `output: standalone` in the next.config.js to build nextjs with a dedicated server.js

**Comment by pustekuchen91** [comment]
hey @danielrotaermel, 
take a look at the thread on the next.js discord server. 
https://discord.com/channels/752553802359505017/1060108314257666088
