### ISSUE TITLE
Concurrent execution of packaged binary fails for the first time, if shared libraries are present

### ISSUE THREAD

**Issue by tecimovic** [vercel/pkg#1829]
### What version of pkg are you using?

5.7.0

### What version of Node.js are you using?

16.17.1

### What operating system are you using?

Fedora Core 35

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node 16, all architectures

### Describe the Bug

Our application includes sqlite3 package, which includes a shared library.

The application is of a type, that is used inside a Jenkins CI environment, in a way where FOR THE FIRST TIME when it is executed, it is executed concurrently. So at about the same time, multiple copies of the application start up around the same time.

We have about 50% of chance to hit this error:
```
Error: EEXIST: file already exists, mkdir '/tmp/pkg/4165e0df889a82cb067406f29cb72916e21edd49c5483fff6b66145eb81d10d0/sqlite3/lib/binding'

    at Object.mkdirSync (node:fs:1349:3)

    at Object.mkdirSync (pkg/prelude/bootstrap.js:1642:33)

    at copyFolderRecursiveSync (pkg/prelude/bootstrap.js:190:8)

    at copyFolderRecursiveSync (pkg/prelude/bootstrap.js:203:9)

    at copyFolderRecursiveSync (pkg/prelude/bootstrap.js:203:9)

    at process.dlopen (pkg/prelude/bootstrap.js:2236:9)

    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)

    at Module.load (node:internal/modules/cjs/loader:981:32)

    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

So in essence what is happening: multiple applications start unpacking around the same time, the '/tmp/pkg/<HASH>' does not yet exist, so multiple application land inside `mkdir` and second one fails.

### Expected Behavior

If multiple executions of the same application start at around the same time, they would be expected to "figure it out", only one creates the /tmp/pkg/<HASH> directory, and the rest of them reuse it.

### To Reproduce

1.) Download linux "asset" from: https://github.com/project-chip/zap/releases/tag/v2022.12.19-nightly
2.) Unzip it, and find `zap-cli` executable.
3.) Run a script like this:
```
#!/bin/bash

rm -rf /tmp/pkg

for A in 1 2 3 4 5 6 7 8 9; do
  zap-cli --version &
done

rm -rf /tmp/pkg
```

**Comment by tecimovic** [comment]
Note: when I run this script on my Linux box, I get a EEXIST failure about 2 out of 5 times I run it. Also:
 
If I modify:
```
[~/git/pkg (main)]$ git diff
diff --git a/prelude/bootstrap.js b/prelude/bootstrap.js
index 034bd15..189fd03 100644
--- a/prelude/bootstrap.js
+++ b/prelude/bootstrap.js
@@ -186,7 +186,11 @@ function copyFolderRecursiveSync(source, target) {
 
   // Check if target folder needs to be created or integrated
   if (!fs.existsSync(targetFolder)) {
-    fs.mkdirSync(targetFolder);
+    try {
+      fs.mkdirSync(targetFolder);
+    } catch (ex) {
+      if (!fs.existsSync(targetFolder)) throw ex;
+    }
   }
 
   // Copy
```
my problems largely go away. I might submit a PR if testing confirms that this solves all my problems...
