### ISSUE TITLE
Error: spawn Unknown system error -8

### ISSUE THREAD

**Issue by rubenhak** [vercel/pkg#1833]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

16.19.0 and 14.17.6

### What operating system are you using?

Linux in container

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14, node16, linux, alpine, win, macos, x64, arm64

### Describe the Bug

Hi,

I'm consistently getting an error `Error: spawn Unknown system error -8` when running inside a CI/CD pipeline. Happens both in Github Workflows and also CodeFresh. Surprisingly running the same locally works fine. 

Runs:
[https://github.com/kubevious/cli/actions/runs/3762138099/jobs/6394548689](https://github.com/kubevious/cli/actions/runs/3762138099/jobs/6394548689)

[https://g.codefresh.io/build/63a4f5c5f5e7eb7cf5a594c5](https://g.codefresh.io/build/63a4f5c5f5e7eb7cf5a594c5)

Error:
```
node:internal/child_process:420
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:733:9)
    at fabricate (/usr/local/lib/node_modules/pkg/lib-es5/fabricator.js:55:51)
    at fabricateTwice (/usr/local/lib/node_modules/pkg/lib-es5/fabricator.js:120:5)
    at MultiStream._queue (/usr/local/lib/node_modules/pkg/lib-es5/producer.js:266:68)
    at MultiStream._next (/usr/local/lib/node_modules/pkg/node_modules/multistream/index.js:86:12)
    at Meter.onEnd (/usr/local/lib/node_modules/pkg/node_modules/multistream/index.js:129:12)
    at Object.onceWrapper (node:events:627:28)
    at Meter.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12) {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
```

Would really appreciate help on this.
Thanks!

### Expected Behavior

The pkg should also work from CI/CD platforms such as Github Workflows or CodeFresh.

### To Reproduce

How to run it locally:
```
$ git clone https://github.com/kubevious/cli.git cli.git
$ docker run -it --rm -v ${PWD}/cli.git:/src --entrypoint bash --workdir /src kubevious/node-executable-builder:v1
```
Inside container:
```
$ yarn
$ pkg . --debug
```

**Comment by robertsLando** [comment]
I never saw such error, I also use pkg in github workflows without any problem. By googling it I found this threads:

https://github.com/brenden/node-webshot/issues/192
https://github.com/puppeteer/puppeteer/issues/9011

> One reason this error may happen is if you spawn() is trying to run a non-Linux binary

The exact line throwing this issue is [this](https://github.com/vercel/pkg/blob/main/lib/fabricator.ts#L71)

Spawn is called using target [nodejs binary](https://github.com/kubevious/cli/actions/runs/3762138099/jobs/6394548689#step:11:42715). This means that you are calling spawn with a node binary that is not a linux binary, the strange thing is that this should work in general... What I could suggest is to try using a custom `PKG_CACHE_PATH` env var to a different location, (a local folder for example just to have the binary in the same 'context')

**Comment by rubenhak** [comment]
@robertsLando, I see that the spawn is a standard nodejs function, but what exactly are you trying to spawn? Which binary is there in the "fabricator.binaryPath" ? Any chance there is an issue with that binary being inconsistent with the platform? I set PKG_CACHE_PATH to a local directory and there was no difference. Still getting the error. 

I checked the environment details, everything look normal:
```
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 23.41 GB / 31.00 GB
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
```

**Comment by robertsLando** [comment]
Like I said in my previous comment spawn is called with the node binary in order to create the bytecode. I have a feel that maybe the env in actions doesn't support this for some reason, maybe when you run a cross os/cross arch binary.

**Comment by argiad** [comment]
Same issue on M1

**Comment by rubenhak** [comment]
@argiad, I ended up using "--no-bytecode" option.
