### ISSUE TITLE
Failed to make bytecode node10-x64 on @aws-sdk/client-s3 v3.272.0

### ISSUE THREAD

**Issue by vorian77** [vercel/pkg#1869]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

18.12.1

### What operating system are you using?

Windows 11

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node10-x64

### Describe the Bug

C:\snapshot\esp-koa-server\node_modules\@aws-sdk\util-stream-browser\dist-es\index.js:1
(function (exports, require, module, __filename, __dirname) { export * from "./getAwsChunkedEncodingStream";
                                                              ^^^^^^
<details>
  <summary>Additional Bugs/Warnings</summary>

SyntaxError: Unexpected token export
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\util-stream-browser\dist-es\index.js:1
(function (exports, require, module, __filename, __dirname) { export * from "./getAwsChunkedEncodingStream";
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\util-stream-browser\dist-es\index.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\endpoint\EndpointParameters.js:7
        useFipsEndpoint: options.useFipsEndpoint ?? false,
                                                  ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\endpoint\EndpointParameters.js:7
        useFipsEndpoint: options.useFipsEndpoint ?? false,
                                                  ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\endpoint\EndpointParameters.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js:34
        bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,
                                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js:34
        bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,
                                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\endpoint\EndpointParameters.js:7
        useDualstackEndpoint: options.useDualstackEndpoint ?? false,
                                                            ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\endpoint\EndpointParameters.js:7
        useDualstackEndpoint: options.useDualstackEndpoint ?? false,
                                                            ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\endpoint\EndpointParameters.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.js:30
        bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,
                                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.js:30
        bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,
                                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:20
    let resolvedPath = `${basePath?.endsWith("/") ? basePath.slice(0, -1) : basePath || ""}` + "/{Key+}";
                                   ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:20
    let resolvedPath = `${basePath?.endsWith("/") ? basePath.slice(0, -1) : basePath || ""}` + "/{Key+}";
                                   ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.shared.js:12
    base64Decoder: config?.base64Decoder ?? util_base64_1.fromBase64,
                          ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.shared.js:12
    base64Decoder: config?.base64Decoder ?? util_base64_1.fromBase64,
                          ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.shared.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\protocols\Aws_query.js:503
        if (input.PolicyArns?.length === 0) {
                             ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\protocols\Aws_query.js:503
        if (input.PolicyArns?.length === 0) {
                             ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\protocols\Aws_query.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.shared.js:11
    base64Decoder: config?.base64Decoder ?? util_base64_1.fromBase64,
                          ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.shared.js:11
    base64Decoder: config?.base64Decoder ?? util_base64_1.fromBase64,
                          ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.shared.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\endpoint\EndpointParameters.js:7
        useDualstackEndpoint: options.useDualstackEndpoint ?? false,
                                                            ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\endpoint\EndpointParameters.js:7
        useDualstackEndpoint: options.useDualstackEndpoint ?? false,
                                                            ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\endpoint\EndpointParameters.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\runtimeConfig.js:28
        bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,
                                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\runtimeConfig.js:28
        bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,
                                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\runtimeConfig.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\protocols\Aws_restJson1.js:13
    const resolvedPath = `${basePath?.endsWith("/") ? basePath.slice(0, -1) : basePath || ""}` + "/federation/credentials";
                                     ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\protocols\Aws_restJson1.js:13
    const resolvedPath = `${basePath?.endsWith("/") ? basePath.slice(0, -1) : basePath || ""}` + "/federation/credentials";
                                     ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\protocols\Aws_restJson1.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\runtimeConfig.shared.js:11
    base64Decoder: config?.base64Decoder ?? util_base64_1.fromBase64,
                          ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\runtimeConfig.shared.js:11
    base64Decoder: config?.base64Decoder ?? util_base64_1.fromBase64,
                          ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso\dist-cjs\runtimeConfig.shared.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\endpoint\EndpointParameters.js:7
        useDualstackEndpoint: options.useDualstackEndpoint ?? false,
                                                            ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\endpoint\EndpointParameters.js:7
        useDualstackEndpoint: options.useDualstackEndpoint ?? false,
                                                            ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\endpoint\EndpointParameters.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\runtimeConfig.js:28
        bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,
                                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\runtimeConfig.js:28
        bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,
                                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\runtimeConfig.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\protocols\Aws_restJson1.js:13
    const resolvedPath = `${basePath?.endsWith("/") ? basePath.slice(0, -1) : basePath || ""}` + "/token";
                                     ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\protocols\Aws_restJson1.js:13
    const resolvedPath = `${basePath?.endsWith("/") ? basePath.slice(0, -1) : basePath || ""}` + "/token";
                                     ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\protocols\Aws_restJson1.js
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\runtimeConfig.shared.js:11
    base64Decoder: config?.base64Decoder ?? util_base64_1.fromBase64,
                          ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\runtimeConfig.shared.js:11
    base64Decoder: config?.base64Decoder ?? util_base64_1.fromBase64,
                          ^

SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> Warning Failed to make bytecode node10-x64 for file C:\snapshot\esp-koa-server\node_modules\@aws-sdk\client-sso-oidc\dist-cjs\runtimeConfig.shared.js

</details>

### Expected Behavior

I expect pkg to package the entire project including the aws modules without warnings/errors.

### To Reproduce

1. Create a node.js project 
2. Add the AWS S3 module: npm i @aws-sdk/client-s3
3. Add an app.js file with const { s3client } = require("@aws-sdk/client-s3");
4. pkg ...app.js -t node10-win-x64 --out-path ...

**Comment by Raduc4** [comment]
Did you find a solution for this?
