### ISSUE TITLE
Could not detect abi for version 18.5.0 and runtime node

### ISSUE THREAD

**Issue by sobolk** [vercel/pkg#1870]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

18.5.0

### What operating system are you using?

Ubuntu 20.10

### What CPU architecture are you using?

x64_64

### What Node versions, OSs and CPU architectures are you building for?

node18-linux-x64

### Describe the Bug

When trying to build `npx pkg -t node18-linux-x64 ../build/node_modules -o ../out/amplify-pkg-linux-x64` (exact command). I'm getting 

```
  throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
  ^

Error: Could not detect abi for version 18.5.0 and runtime node.  Updating "node-abi" might help solve this issue if it is a new release of node
    at getAbi (/home/circleci/repo/node_modules/node-abi/index.js:36:9)
    at module.exports (/home/circleci/repo/node_modules/prebuild-install/rc.js:52:57)
    at Object.<anonymous> (/home/circleci/repo/node_modules/prebuild-install/bin.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
 ```

### Expected Behavior

There's no error.

### To Reproduce

Package any application with `-t node18-linux-x64` (or any `node18`) with latest (as of today) `pkg@5.8.0`.

FWIW. The fix seems to be merged, i.e. here https://github.com/vercel/pkg/pull/1788 . Could you please release it?

**Comment by tillderoquefeuil** [comment]
Same here!

Currently doing ```pnpm i -D "https://github.com/vercel/pkg"```
