### ISSUE TITLE
node cluster module setupPrimary execArgv causes loader error

### ISSUE THREAD

**Issue by rgillan** [vercel/pkg#1880]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

18.5.0

### What operating system are you using?

ubuntu 18.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node18-linux

### Describe the Bug

Have a nodejs application using the cluster module.  Running from the command line, it works correctly and forks worker instances.  We need to apply --max-old-memory-size=4096 to the workers.

using cluster.setupPrimary({execArgv:['--max-old-space-size=4096']}) from the command line works correctly:
` 9676 pts/1    Sl+    0:00 node stage1c.js
 9683 pts/1    Sl+    0:00 /usr/bin/node --max-old-space-size=4096 /opt/nisient/lib/node/stage1c.js
 9690 pts/1    Sl+    0:00 /usr/bin/node --max-old-space-size=4096 /opt/nisient/lib/node/stage1c.js
`
if we pkg -t node18-linux stage1c.js, we then get errors on execution and only one worker started:
`13365 pts/1    Rl+    0:00 ./stage1c
13635 pts/1    Rl+    0:00 /opt/nisient/lib/node/stage1c --max-old-space-size=4096 /snapshot/node/stage1c.js
`
and the execution error (repeating):
`Thu Mar 09 2023 06:17:26 GMT+0000 (Coordinated Universal Time) (s1):13365 worker died: 14082:undefined
node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module '/opt/nisient/lib/node/--max-old-space-size=4096'
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.5.0
`
If we try excluding the setupPrimary in the code, and apply the option from the pkg step (pkg -t node18-linux --options "max-old-space-size=4096" stage1c.js), we see the two worker instances started:
`14326 pts/1    Sl+    0:00 ./stage1c
14554 pts/1    Rl+    0:00 /opt/nisient/lib/node/stage1c --max-old-space-size=4096 /snapshot/node/stage1c.js
14555 pts/1    Rl+    0:00 /opt/nisient/lib/node/stage1c --max-old-space-size=4096 /snapshot/node/stage1c.js
`
but still a repeating execution error:
`Thu Mar 09 2023 06:20:29 GMT+0000 (Coordinated Universal Time) (s1):14326 worker died: 15074:undefined
node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module '/opt/nisient/lib/node/--max-old-space-size=4096'
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.5.0
`

### Expected Behavior

We expect that the cluster workers will be passed the V8 options without causing error

### To Reproduce

const cluster = require('cluster');

let workerMap = {};
let workerStartDelay = 0;

if (cluster.isPrimary) {

	cluster.setupPrimary({
		execArgv: ['--max-old-space-size=4096']
	});

	let worker = cluster.fork();
	worker.send({cmd: 'setWorkerId', workerId: 0});

	for (i = 1; i < 2; i++) {

		workerStartDelay = i * 100;

		setTimeout((i) => {
			let worker = cluster.fork();
			worker.send({cmd: 'setWorkerId', workerId: 1});
		}, 1000, i);

	}

	cluster.on('exit', (worker, code, signal) => {

		let workerId = workerMap[worker.process.pid];

		delete workerMap[worker.process.pid];

		console.log('worker died: ' + worker.process.pid + ':' + workerId);

		let newWorker = cluster.fork();
		newWorker.send({cmd: 'setWorkerId', workerId: workerId});

	});

	for (var id in cluster.workers) {

		cluster.workers[id].on('message', (msg) => {
			workerMap[msg.processPid] = msg.workerId
		});

	}

} else {

	process.on('message', (msg) => {
		console.log('msg:' + JSON.stringify(msg))
		process.send({ cmd: 'setWorkerId', processPid: process.pid, workerId: msg.workerId });
	});

}

**Comment by rgillan** [comment]
see there has been earlier issues/pull request for child_process.fork and references in
[https://github.com/vercel/pkg/issues/334](url)
[https://github.com/vercel/pkg/issues/909](url)
Any update on this would be very much appreciated

**Comment by rgillan** [comment]
So in case anyone else needs this as a workaround, if you set args and execArgv to empty arrays prior to the fork, it will inherit the --options set in the pkg command line, e.g.
`		cluster.setupPrimary({
			args: [],
			execArgv: []
		});
`
