### ISSUE TITLE
EXE crash when i build with the Serialport Lib

### ISSUE THREAD

**Issue by nikolajhusted** [vercel/pkg#1903]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

18.5.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

node18-win-x64

### What Node versions, OSs and CPU architectures are you building for?

node18

### Describe the Bug

i have aproblem when i have made the build the exe file crashes emitietly when i use the Serialport lib like this:
`const { SerialPort } = require('serialport');`

but if i comment it out and build the exe file again, then there is no problems anymore.

### Expected Behavior

to know if i do anything wrong.

### To Reproduce

```
//////////////////////////////////////////
//Settings

//lib includes

const { SerialPort } = require('serialport');
const { ReadlineParser } = require('@serialport/parser-readline');
var ks = require('node-key-sender');

//key settings
ks.setOption('globalDelayBetweenMillisec', 1000);

  //function setup(){

    let config = require('./config.json');
    // port setupsettings
    let Dport = config["index-Port"];
    let baudRate = config["Baudrate"];
    const COM = config["Com-Port"];

    console.log(" -> Parameter er sat!!");
    
    ///////////////////////////////////////////
    //server

    //keystroke map
    var keyMap = [];
    keyMap["X00"+Dport+"A[1]"] = config.Keymap["Key1"];
    keyMap["X00"+Dport+"A[2]"] = config.Keymap["Key2"];
    keyMap["X00"+Dport+"A[3]"] = config.Keymap["Key3"];
    keyMap["X00"+Dport+"A[4]"] = config.Keymap["Key4"];
    keyMap["X00"+Dport+"A[5]"] = config.Keymap["Key5"];
    keyMap["X00"+Dport+"A[6]"] = config.Keymap["Key6"];
    keyMap["X00"+Dport+"A[7]"] = config.Keymap["Key7"];
    keyMap["X00"+Dport+"A[8]"] = config.Keymap["Key8"];
    keyMap["X00"+Dport+"A[9]"] = config.Keymap["Key9"];
    keyMap["X00"+Dport+"A[10]"] = config.Keymap["Key10"];
    console.log(" -> KeyMap er lavet");
  // Create a port
    port = new SerialPort({
      path: COM,
      baudRate: baudRate
    },
    function (err) {
      if (err) {
        return console.log('Error: ', err.message);
      }
    });
  
    console.log(" -> Server er klar og startet op");





//function
const parser = port.pipe(new ReadlineParser({ delimiter: '\r\n' }));

parser.on('data', function(data) {
 console.log(" -> ACSII kode der blev kald: "+ data+" - Der blev trykket på: "+ keyMap[data]);
  //ks.sendKey(keyMap[data]);
})

```

When i run the app.exe fil i get the following in the command prompt:

```
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: No native build was found for platform=win32 arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.5.0       
    loaded from: C:\snapshot\ASCIItoKey\node_modules\@serialport\bindings-cpp

    at Function.<anonymous> (C:\snapshot\ASCIItoKey\node_modules\node-gyp-build\node-gyp-build.js:60:9)
    at load (C:\snapshot\ASCIItoKey\node_modules\node-gyp-build\node-gyp-build.js:22:30)
    at Object.<anonymous> (C:\snapshot\ASCIItoKey\node_modules\@serialport\bindings-cpp\dist\load-bindings.js:11:46)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)

Node.js v18.5.0
```

**Comment by trek-eric** [comment]
i'm having the same issue  - have you found a solution here yet?

**Comment by nikolajhusted** [comment]
@trek-eric i found out that it´s easier to downgrad to Serialport 9.2.8, and then rewrite your code a little.

**Comment by rotu** [comment]
I had the same issue. I fixed it by adding the `.node` file as as asset in package.json:

```
{
   // "name": "my-package",
   // ...
   "pkg": {
      "assets": [
         "node_modules/@serialport/**/*.node"
      ]
   }
}
```

I have a pre-package esbuild task as well, in which I needed to externalize both `serialport` and `@serialport/bindings-cpp`:

```
esbuild --bundle main.js --outfile=dist/main.cjs --platform=node --format=cjs --external:@serialport/bindings-cpp --external:serialport
```

**Comment by robertsLando** [comment]
Just add bindings to assets:

```
"pkg": {
		"assets": [
			"./node_modules/@serialport/bindings-cpp/**",
		]
	},
```

**Comment by nyszilard** [comment]
I have the same problem.
```
node: 18.16.0
pkg: 5.8.1
os: windows 10 x64
cpu-architecture: node18-win-x64
```

`npm init -y`
`npm install serialport`

**package.json:**
```json
{
  "name": "cardreader",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "pkg": {
    "assets": [
      "./node_modules/@serialport/bindings-cpp/**"
    ]
  },
  "dependencies": {
    "serialport": "^10.5.0"
  }
}
```

**index.js**
`const { SerialPort } = require('serialport')`

**commands:**
```
pkg index.js --output myapp.exe --targets host
.\myapp.exe
```

**ERROR:**
```
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: No native build was found for platform=win32 arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.5.0
    loaded from: C:\snapshot\cardreader\node_modules\@serialport\bindings-cpp

    at Function.<anonymous> (C:\snapshot\cardreader\node_modules\node-gyp-build\node-gyp-build.js:60:9)
    at load (C:\snapshot\cardreader\node_modules\node-gyp-build\node-gyp-build.js:22:30)
    at Object.<anonymous> (C:\snapshot\cardreader\node_modules\@serialport\bindings-cpp\dist\load-bindings.js:11:46)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)

Node.js v18.5.0
```

**Comment by nyszilard** [comment]
The last version that still works for me:
```json
"dependencies": {
    "serialport": "10.0.0"
}
```
