### ISSUE TITLE
Not working with selenium-webdriver

### ISSUE THREAD

**Issue by Rylazius** [vercel/pkg#2012]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

18.16.0

### What operating system are you using?

Windows 10 21H2

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node18-win-x64

### Describe the Bug

Doesn't work with selenium-webdriver

### Expected Behavior

I pack my index.js with pkg and no errors, when run it, i got this:
```
../../../bazel-bin/javascript/node/selenium-webdriver/lib/atoms/get-attribute.js
Error: Cannot find module 'D:\bazel-bin\javascript\node\selenium-webdriver\lib\atoms\get-attribute.js'
Require stack:
- C:\snapshot\testing\node_modules\selenium-webdriver\lib\http.js
- C:\snapshot\testing\node_modules\selenium-webdriver\http\index.js
- C:\snapshot\testing\node_modules\selenium-webdriver\index.js
- C:\snapshot\testing\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireAtom (C:\snapshot\testing\node_modules\selenium-webdriver\lib\http.js:62:14)
    at Object.<anonymous> (C:\snapshot\testing\node_modules\selenium-webdriver\lib\http.js:37:22)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\snapshot\\testing\\node_modules\\selenium-webdriver\\lib\\http.js',
    'C:\\snapshot\\testing\\node_modules\\selenium-webdriver\\http\\index.js',
    'C:\\snapshot\\testing\\node_modules\\selenium-webdriver\\index.js',
    'C:\\snapshot\\testing\\index.js'
  ]
}

...
```

index.js
```
const { Builder, By } = require('selenium-webdriver');

...
```

### To Reproduce

1. Use selenium-webdriver
2. Pack with pkg
3. Run

**Comment by wangximingit** [comment]
I also have no problem with packaging, but there is a problem with running the report

pkg/prelude/bootstrap.js:1872
      throw error;
      ^

TypeError: log_.error is not a function
    at requireAtom (C:\snapshot\node\node_modules\.pnpm\selenium-webdriver@4.15.0\node_modules\selenium-webdriver\lib\http.js:66:12)
    at Object.<anonymous> (C:\snapshot\node\node_modules\.pnpm\selenium-webdriver@4.15.0\node_modules\selenium-webdriver\lib\http.js:39:22)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\node\node_modules\.pnpm\selenium-webdriver@4.15.0\node_modules\selenium-webdriver\http\index.js:29:17)

**Comment by Amine-kun** [comment]
> I also have no problem with packaging, but there is a problem with running the report
> 
> pkg/prelude/bootstrap.js:1872 throw error; ^
> 
> TypeError: log_.error is not a function at requireAtom (C:\snapshot\node\node_modules.pnpm\selenium-webdriver@4.15.0\node_modules\selenium-webdriver\lib\http.js:66:12) at Object. (C:\snapshot\node\node_modules.pnpm\selenium-webdriver@4.15.0\node_modules\selenium-webdriver\lib\http.js:39:22) at Module._compile (pkg/prelude/bootstrap.js:1926:22) at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) at Module.load (node:internal/modules/cjs/loader:988:32) at Module._load (node:internal/modules/cjs/loader:834:12) at Module.require (node:internal/modules/cjs/loader:1012:19) at Module.require (pkg/prelude/bootstrap.js:1851:31) at require (node:internal/modules/cjs/helpers:102:18) at Object. (C:\snapshot\node\node_modules.pnpm\selenium-webdriver@4.15.0\node_modules\selenium-webdriver\http\index.js:29:17)

i encountered the same issue, have you found anything useful?
