### ISSUE TITLE
Formidable support

### ISSUE THREAD

**Issue by dpeter99** [vercel/pkg#224]
I need some help with formidable (form handler with file upload support).

```
Error: File or directory 'P:\**\FileUpload\uploads\tmp\upload_2ecfe7ad92c3fb73003a94f1c44d6db3.mp3' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:405:17)
    at openFromSnapshot (pkg/prelude/bootstrap.js:448:29)
    at Object.fs.open (pkg/prelude/bootstrap.js:484:5)
    at WriteStream.open (fs.js:2082:6)
    at new WriteStream (fs.js:2068:10)
    at File.open (P:\snapshot\FileUpload\node_modules\formidable\lib\file.js:34:23)
    at IncomingForm.handlePart (P:\snapshot\FileUpload\node_modules\formidable\lib\incoming_form.js:213:8)
    at IncomingForm.onPart (P:\snapshot\FileUpload\node_modules\formidable\lib\incoming_form.js:177:8)
    at MultipartParser.IncomingForm._initMultipart.parser.onHeadersEnd (P:\snapshot\FileUpload\node_modules\formidable\lib\incoming_form.js:412:10)
    at callback (P:\snapshot\FileUpload\node_modules\formidable\lib\multipart_parser.js:102:31)
    at MultipartParser.write (P:\snapshot\FileUpload\node_modules\formidable\lib\multipart_parser.js:215:9)```

**Comment by igorklopov** [comment]
You need to set `uploadDir` (https://www.npmjs.com/package/formidable#formidableincomingform) to something related to `path.dirname(process.execPath)`. If you need to support running both in pkg'ed state and in node, check `process.pkg`.
```js
if (process.pkg) {
  file.upload = path.join(path.dirname(process.execPath), 'temp');
} else {
  file.upload = path.join(__dirname, 'temp');
}
```

**Comment by leerob** [comment]
Closing as stale 🙏 Thank you!
