### ISSUE TITLE
Bindings module pcslite

### ISSUE THREAD

**Issue by FPalu** [vercel/pkg#253]
Hello everyone, 
I get this error when I try to run the executable on another machine

pkg/prelude/bootstrap.js:1155
     throw error;
     ^

Error: Could not locate the bindings file. Tried:
→ C:\snapshot\fpa\node_modules\pcsclite\build\pcsclite.node
→ C:\snapshot\fpa\node_modules\pcsclite\build\Debug\pcsclite.node
→ C:\snapshot\fpa\node_modules\pcsclite\build\Release\pcsclite.node
→ C:\snapshot\fpa\node_modules\pcsclite\out\Debug\pcsclite.node
→ C:\snapshot\fpa\node_modules\pcsclite\Debug\pcsclite.node
→ C:\snapshot\fpa\node_modules\pcsclite\out\Release\pcsclite.node
→ C:\snapshot\fpa\node_modules\pcsclite\Release\pcsclite.node
→ C:\snapshot\fpa\node_modules\pcsclite\build\default\pcsclite.node
→ C:\snapshot\fpa\node_modules\pcsclite\compiled\8.0.0\win32\x64\pcsclite.node
   at bindings (C:\snapshot\fpa\node_modules\bindings\bindings.js:93:9)
   at Object.<anonymous> (C:\snapshot\fpa\node_modules\pcsclite\lib\pcsclite.js:5:35)
   at Module._compile (pkg/prelude/bootstrap.js:1226:22)
   at Object.Module._extensions..js (module.js:580:10)
   at Module.load (module.js:503:32)
   at tryModuleLoad (module.js:466:12)
   at Function.Module._load (module.js:458:3)
   at Module.require (module.js:513:17)
   at Module.require (pkg/prelude/bootstrap.js:1136:31)
   at require (internal/module.js:11:18)

I miss someting?  

Thx

**Comment by zachariahtimothy** [comment]
I am experiencing the same issue on another library ([microtime](https://github.com/wadey/node-microtime)). @FPalu did you find a resolution?

**Comment by FPalu** [comment]
Hello, 

No I didn't find a solution.

I did this same code with a different language (C#)

**Comment by zachariahtimothy** [comment]
Cool thanks @FPalu . I was able to skip using microtime and write a small helper instead. Have a great one!

**Comment by jeppech** [comment]
@FPalu I don't know if you ever found a solution, but I'm also using pcsclite, in my compiled nodejs binary, and it works.
I had to copy the following native modules: `buffertools.node`, `pcsclite.node` and `unix_dgram.node` to the same folder as my executable. So my folder looks like this:

```
jc-debian:flexhotel $ ls -la
total 39900
drwxr-xr-x 2 root root      4096 Feb  7 14:02 .
drwxrwsr-x 8 root staff     4096 Feb  7 13:57 ..
-rwxr-xr-x 1 root root     28520 Feb  2 14:10 buffertools.node
-rwxr-xr-x 1 root root  40708470 Feb  2 14:10 flexhotel
-rwxr-xr-x 1 root root     74128 Feb  7 14:02 pcsclite.node
-rwxr-xr-x 1 root root     31152 Feb  7 14:02 unix_dgram.node
```

Though, I am unsure if this will work on windows too.

**Comment by Suprincesu** [comment]
same issue but in onoff js.
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 → /snapshot/qms_gpio/node_modules/epoll/build/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/build/Debug/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/build/Release/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/out/Debug/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/Debug/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/out/Release/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/Release/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/build/default/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/compiled/8.11.3/linux/arm/epoll.node
    at bindings (/snapshot/qms_gpio/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/snapshot/qms_gpio/node_modules/epoll/epoll.js:1:99)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
