### ISSUE TITLE
Error: Cannot find module './'

### ISSUE THREAD

**Issue by erikd** [vercel/pkg#315]
I'm an experienced dev, but really new to node.

I'm using `pkg` to build an executable, but when run it fails with:
```
Error: Cannot find module './'
1) If you want to compile the package/file into executable, please pay attention to 
 compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile
 the package/file into executable and want to 'require' it from filesystem (likely plugin),
 specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snapshot/daedalus/node_modules/.bin/electron:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32
```
I'm perfectly happy to accept there is something wrong with this code, but it would be nice to have some better debug info.

**Comment by dunklesToast** [comment]
For debug use the `-d` argument!

**Comment by BenGermany** [comment]
I have the same issues and this runs some month ago?!

https://github.com/zeit/pkg/issues/334

**Comment by shahajipatil** [comment]
I have the same issue unable to find exact solution

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
