### ISSUE TITLE
Error on compiling: AssertionError [ERR_ASSERTION]: Placeholder for not found

### ISSUE THREAD

**Issue by andreaneri** [vercel/pkg#323]
hi there, i'm trying to compile my nodejs script, this is the error that i get:

pkg --target node8-linux-x64 -o ./ex_ora ./ex_ora.js
> pkg@4.3.0-beta.5
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Placeholder for not found
    at injectPlaceholder (/usr/local/lib/node_modules/pkg/lib-es5/producer.js:217:38)
    at injectPlaceholders (/usr/local/lib/node_modules/pkg/lib-es5/producer.js:236:3)
    at /usr/local/lib/node_modules/pkg/lib-es5/producer.js:158:9
    at FSReqWrap.oncomplete (fs.js:135:15)

and this is my workstation:
Darwin Macintosh.local 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64

thanks,

Andrea

**Comment by FatKiwi** [comment]
Same here, on Windows x64 build:
`AssertionError [ERR_ASSERTION]: Placeholder for not found
    at injectPlaceholder (\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:217:38)
    at injectPlaceholders (\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:236:3)
    at \AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:158:9
    at FSReqWrap.oncomplete (fs.js:149:20)`

**Comment by roccomuso** [comment]
I'm having the same issue on Ubuntu 16.04

**Comment by adonespitogo** [comment]
Has anyone found a solution? Got same error on archlinux arm, node 9.2.1

**Comment by dtzq01** [comment]
Here I downloaded the wrong Node.js binaries(from https://nodejs.org/download/release/) due to can not download bin automatically, it should be here(https://github.com/vercel/pkg-fetch/releases). 

AssertionError [ERR_ASSERTION]: Placeholder for not found
    at injectPlaceholder (C:\Users\XXX\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:46:37)
    at injectPlaceholders (C:\Users\XXX\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:66:3)
    at C:\Users\XXX\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:224:9
    at FSReqCallback.oncomplete (fs.js:155:23) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by cement** [comment]
The same question,  Windows x64 build:

**Comment by cement** [comment]
> pkg@4.4.9
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Placeholder for not found

**Comment by jesec** [comment]
You must use patched binaries. 

See https://github.com/vercel/pkg-fetch .
