### ISSUE TITLE
log4js - unable to log

### ISSUE THREAD

**Issue by santoshnair** [vercel/pkg#353]
Hello, I am using "log4js" in my project, but when the build is compiled and run I get this error. Seems like the logger is unable to write to the "logs" directory.
here is the error stack
Error: write after end
    at writeAfterEnd (_stream_writable.js:195:12)
    at RotatingFileStream.Writable.write (_stream_writable.js:242:5)
    at Array.logRequest (D:\snapshot\ezeechatbot\node_modules\morgan\index.js:130:14)
    at listener (D:\snapshot\ezeechatbot\node_modules\on-finished\index.js:169:15)
    at onFinish (D:\snapshot\ezeechatbot\node_modules\on-finished\index.js:100:5)
    at callback (D:\snapshot\ezeechatbot\node_modules\ee-first\index.js:55:10)
    at ServerResponse.onevent (D:\snapshot\ezeechatbot\node_modules\ee-first\index.js:93:5)
    at emitNone (events.js:91:20)
    at ServerResponse.emit (events.js:185:7)
    at finish (_http_outgoing.js:595:10)

**Comment by gpye** [comment]
#359 #286 
Assume you are writing logs into snapshot, it is not supported(read only not write). Try place logs in the same dir as your executable using `process.execPath`.

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!

**Comment by noszone** [comment]
If anyone could give advise on the similar issue where I need to pass a variable from server to client part? I've wrote the issue on SO: [https://stackoverflow.com/questions/66883900/is-it-possible-to-use-a-react-server-enviroment-variables-into-frontend-at-clien](url)

**Comment by hipstersmoothie** [comment]
@leerob Could we open up discussion? I think it would be useful for support requests

**Comment by robertsLando** [comment]
+1 for discussions
