### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by pigcan** [vercel/pkg#370]
checkout https://github.com/pigcan/cnpm

```bash
$npm run pkg
```
then

```js
//test.js
const { spawn } = require('child_process');

const child = spawn('/Path/To/Executable/cnpm', ['install', 'cygnus-ide-umi-project']);

child.stdout.on('data', (data) => {
  console.log(data.toString());
});

child.stderr.on('data', (data) => {
  console.log(data.toString());
});

child.on('exit', (code) => {
  console.log(`Child exited with code ${code}`);
});
```

```bash
node test.js
```

----

```
module.js:536
    throw err;
    ^

Error: Cannot find module 'scripts/install.js'
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:464:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1298:12)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3

Error: post install error, please remove node_modules before retry!
Run "sh -c node scripts/install.js" error, exit code 1
    at ChildProcess.module.exports.proc.on.code (/snapshot/cnpm/node_modules/runscript/index.js:74:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by andywer** [comment]
Yeah, looks like we have the same issue over here at andywer/threads.js#92. pkg's snapshot filesystem doesn't work with `child_process.fork`/`.spawn`, at least not out of the box...

@igorklopov Is there a known workaround?

**Comment by hipstersmoothie** [comment]
You would need to include these files as an asset or script
