### ISSUE TITLE
Packaging with node-thrust : issue when run

### ISSUE THREAD

**Issue by mahmed0715** [vercel/pkg#378]
Hi,
I was wondering if there is any solution about the issue with running exe that runs node-thrust on top of the api server.
Error coming up when run the exe:  
```
[2018-03-18T07:44:27.913Z] SPAWING /snapshot/node-trust-test/node_modules/node-thrust/vendor/thrust/thrust_shell
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /snapshot/node-trust-test/node_modules/node-thrust/vendor/thrust/thrust_shell ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at run (bootstrap_node.js:419:7)
    at startup (bootstrap_node.js:185:9)
    at bootstrap_node.js:532:3
```
Please help.
TIA..
Mustak

**Comment by haiyangwu** [comment]
same question

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
