### ISSUE TITLE
Cannot write to packaged file

### ISSUE THREAD

**Issue by jschlanger12** [vercel/pkg#388]
I am attempting to package an express with express-admin app but keep getting this:
```
C:\snapshot\monolith_backend\node_modules\sqlite3\lib\trace.js:27
                    throw err;
                    ^

Error: Cannot write to packaged file
    at writeToSnapshot (pkg/prelude/bootstrap.js:567:16)
    at Object.fs.writeSync (pkg/prelude/bootstrap.js:575:12)
    at Object.fs.writeFileSync (fs.js:1301:24)
    at C:\snapshot\monolith_backend\node_modules\express-admin\app.js:83:20
    at C:\snapshot\monolith_backend\node_modules\express-admin\lib\db\schema.js:42:9
    at done (C:\snapshot\monolith_backend\node_modules\express-admin\node_modules\async\lib\async.js:135:19)
    at _toString (C:\snapshot\monolith_backend\node_modules\express-admin\node_modules\async\lib\async.js:32:16)
    at done (C:\snapshot\monolith_backend\node_modules\express-admin\node_modules\async\lib\async.js:135:19)
    at _toString (C:\snapshot\monolith_backend\node_modules\express-admin\node_modules\async\lib\async.js:32:16)
    at C:\snapshot\monolith_backend\node_modules\express-admin\lib\db\schema.js:37:21
--> in Database#all('pragma table_info(\'sqlite_sequence\') ;', [Function])
    at SQLite.query (C:\snapshot\monolith_backend\node_modules\express-admin\lib\db\client.js:181:25)
    at Object.exports.getColumns (C:\snapshot\monolith_backend\node_modules\express-admin\lib\db\schema.js:20:12)
    at C:\snapshot\monolith_backend\node_modules\express-admin\lib\db\schema.js:33:25
    at C:\snapshot\monolith_backend\node_modules\express-admin\node_modules\async\lib\async.js:125:13
    at Array.forEach (<anonymous>)
    at _each (C:\snapshot\monolith_backend\node_modules\express-admin\node_modules\async\lib\async.js:46:24)
    at Object.async.each (C:\snapshot\monolith_backend\node_modules\express-admin\node_modules\async\lib\async.js:124:9)
    at C:\snapshot\monolith_backend\node_modules\express-admin\lib\db\schema.js:32:19
    at C:\snapshot\monolith_backend\node_modules\express-admin\lib\db\schema.js:11:9
```

Does it have something to do with writing to the snapshot files? If so how would i change it so that it doesn't do that and write to local files?

**Comment by Jucesr** [comment]
@jschlanger12 did you find any solution?

**Comment by theone3nu** [comment]
Same here facing the problem. Any soluton yet please?

**Comment by princenaman** [comment]
+1

**Comment by marksink** [comment]
I had the same issue and fixed it by using this:

var filePath = process.cwd()+'/your_file_here.ext';

From the instruction, it says: "On the other hand, in order to access real file system at run time (pick up a user's external javascript plugin, json configuration or even get a list of user's directory) you should take process.cwd() or path.dirname(process.execPath)."

**Comment by Ceeson** [comment]
> I had the same issue and fixed it by using this:
> 
> var filePath = process.cwd()+'/your_file_here.ext';
> 
> From the instruction, it says: "On the other hand, in order to access real file system at run time (pick up a user's external javascript plugin, json configuration or even get a list of user's directory) you should take process.cwd() or path.dirname(process.execPath)."

thanks，it's works.  I use "process.cwd()" replace "__dirname" then it works.
