### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mikhail-manuilov** [vercel/pkg#391]
After many different tries to build docker container using multi stage build (finally for some reason have to create `/snapshot/code` directory in target container, though pkg was running in `/code` in build container got 
`RangeError: Maximum call stack size exceeded` error:

```
RUN npm install -g pkg pkg-fetch
 ---> Running in a75c49ab062b
/usr/local/bin/pkg-fetch -> /usr/local/lib/node_modules/pkg-fetch/lib-es5/bin.js
/usr/local/bin/pkg -> /usr/local/lib/node_modules/pkg/lib-es5/bin.js
+ pkg-fetch@2.5.4
+ pkg@4.3.1

RUN pkg --targets ${NODE}-${PLATFORM}-${ARCH} -o index app.js
 ---> Running in a8c3d2b7cea1
> pkg@4.3.1
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  /code/node_modules/websocket/build/Release/bufferutil.node
  path-to-executable/bufferutil.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  /code/node_modules/websocket/build/Release/validation.node
  path-to-executable/validation.node

Step 54/57 : RUN ls -laR /snapshot/code
 ---> Running in 2e1b3495564f
/snapshot/code:
total 141296
drwxr-xr-x 1 root root      4096 Apr  3 09:11 .
drwxr-xr-x 1 root root      4096 Apr  3 09:11 ..
-rwxr-xr-x 1 root root     56568 Apr  2 17:30 bcrypt_lib.node
-rwxr-xr-x 1 root root     23144 Apr  2 17:30 bufferutil.node
-rwxr-xr-x 1 root root 144561397 Apr  2 17:34 index
drwxr-xr-x 1 root root      4096 Apr  3 09:11 node_modules
drwxr-xr-x 1 root root      4096 Apr  3 09:11 templates
-rwxr-xr-x 1 root root     22384 Apr  2 17:30 validation.node

+ /snapshot/code/index
app          | pkg/prelude/bootstrap.js:1172
app          |       throw error;
app          |       ^
app          | 
app          | RangeError: Maximum call stack size exceeded
app          |     at insideSnapshot (pkg/prelude/bootstrap.js:1650:52)
app          |     at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:216:8)
app          |     at findNativeAddonForExists (pkg/prelude/bootstrap.js:995:21)
app          |     at existsFromSnapshot (pkg/prelude/bootstrap.js:1004:25)
app          |     at Object.fs.existsSync (pkg/prelude/bootstrap.js:1016:12)
app          |     at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:220:21)
app          |     at findNativeAddonForExists (pkg/prelude/bootstrap.js:995:21)
app          |     at existsFromSnapshot (pkg/prelude/bootstrap.js:1004:25)
app          |     at Object.fs.existsSync (pkg/prelude/bootstrap.js:1016:12)
app          |     at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:220:21)
app          |     at findNativeAddonForExists (pkg/prelude/bootstrap.js:995:21)
app          |     at existsFromSnapshot (pkg/prelude/bootstrap.js:1004:25)
app          |     at Object.fs.existsSync (pkg/prelude/bootstrap.js:1016:12)
app          |     at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:220:21)
app          |     at findNativeAddonForExists (pkg/prelude/bootstrap.js:995:21)
app          |     at existsFromSnapshot (pkg/prelude/bootstrap.js:1004:25)
app          |     at Object.fs.existsSync (pkg/prelude/bootstrap.js:1016:12)
app          |     at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:220:21)
app          |     at findNativeAddonForExists (pkg/prelude/bootstrap.js:995:21)
app          |     at existsFromSnapshot (pkg/prelude/bootstrap.js:1004:25)
app          |     at Object.fs.existsSync (pkg/prelude/bootstrap.js:1016:12)
app          |     at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:220:21)
app exited with code 1
```

**Comment by gpye** [comment]
This could be a possible explanantion - I believe you are not allowed to write into /snapshot as per igorklopov's comment in #381. I was seeing the same error until I realized it might as well be the system's way of attempting writing into snapshot with constant failure.
