### ISSUE TITLE
Cannot find module ./tedious

### ISSUE THREAD

**Issue by danielegli** [vercel/pkg#402]
Hi, I've been trying to pkg a node app that includes "seriate" for database functionality.  As soon as I require seriate, I encounter the following error: 
`Error: Cannot find module './tedious'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:540:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:583:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at new Connection (C:\snapshot\web\node_modules\mssql\lib\main.js:177:45)
    at connect (C:\snapshot\web\node_modules\seriate\src\connections.js:61:31)
    at Object.addConnection [as add] (C:\snapshot\web\node_modules\seriate\src\connections.js:34:10)
    at Object.setDefaultConfig (C:\snapshot\web\node_modules\seriate\src\index.js:75:15)`

It looks like you have a dictionary with additional scripts for various modules, but I wasn't able to replicate a solution for seriate/tedious. Any insight on this?

**Comment by jremi** [comment]
how did you solve this?

**Comment by danielegli** [comment]
By using the mssql module instead of seriate
