### ISSUE TITLE
Cannot find module './module'

### ISSUE THREAD

**Issue by piyush005** [vercel/pkg#403]
pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: Cannot find module './module'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/backend/node_modules/datauri/index.js:10:18)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/backend/node_modules/rgba-to-datauri/index.js:4:17)

**Comment by SteveEdson** [comment]
I'm also getting this issue with node `v10.9.0` as well as ` v6.14.3`, any ideas?

Thanks.

**Comment by SteveEdson** [comment]
Ah, the issue is due to the `datauri` module being used by one of my dependencies, see the file https://github.com/data-uri/datauri/blob/master/index.js.

Is there a way to resolve this in pkg, or does it need to be changed upstream?

Thanks

**Comment by adyayana** [comment]
Is there any solution to this problem, mee to facing the same issue.
