### ISSUE TITLE
Jaeger.thrift was not included into executable at compilation stage. Please recompile adding it as asset or script.

### ISSUE THREAD

**Issue by Fumler** [vercel/pkg#410]
Hello.

Trying to use pkg with a nextjs app. It compiles just fine but when we try to run the binary we get an error:

```
Error: File '/**/project/node_modules/jaeger-client/dist/src/jaeger-idl/thrift/jaeger.thrift' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:422:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:646:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:689:18)
    at Object.<anonymous> (/snapshot/project/node_modules/jaeger-client/dist/src/thrift.js:168:24)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:650:10)
    at Module.load (module.js:558:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:583:17)
```

I tried adding jaeger.thrift to assets and scripts but I get the same error message.
E.g.
```json
"pkg": {
	"assets": [
		".next",
		"pages",
		"node_modules/jaeger-client/dist/src/jaeger-idl/thrift/jaeger.thrift"
	],
	"scripts": [".next/dist/**/*.js"]
}
```

Any ideas to how I can fix this?

**Comment by nemik** [comment]
was running into this same problem. I ended up adding it to the `assets` part with:
`"./node_modules/jaeger-client/dist/src/jaeger-idl/thrift/jaeger.thrift"`

and that worked.
