### ISSUE TITLE
node-webcam - Cannot find module '/snapshot/nido/node_modules/node-webcam/src/Factory.js'

### ISSUE THREAD

**Issue by serra82** [vercel/pkg#426]
pkg return the following error to produce the binary of my software that use node-webcam module.
The error is easy reprodicible using the example code on repo: https://github.com/chuckfairy/node-webcam

pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: Cannot find module '/snapshot/webcam/node_modules/node-webcam/src/Factory.js'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/webcam/node_modules/node-webcam/index.js:21:14)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)

If I run pkg with debug enable I see this error:

> [debug] Cannot resolve '__dirname + '/src/Factory.js''
  /home/serra82/tmp/webcam/node_modules/node-webcam/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.

to compile correctly I have to remove all '__dirname +' from require in source file of node-webcam; is there better way to resolve the problem?

Thank you

**Comment by hipstersmoothie** [comment]
closing in favor of #477
