### ISSUE TITLE
not able to include npm modules without changing their package.json

### ISSUE THREAD

**Issue by pkgulati** [vercel/pkg#454]
If my main application uses a node_module which has some config or json files, I am unable to use pkg without changing package.json of that node_module. I should be able to configure assets and scripts of npm modules by changing my package.json instead of package.json of dependent modules. 

I have added a sample project for this at [github](https://github.com/pkgulati/testnodeexe)

The sample app is using a node module testpkg1.

If I change node_modules/testpkg1/package.json to specify

```
"pkg" : { "assets": [ "dir1", "dir2"]},
```

The app works fine with pkg. However if I change my own package.json (root level) to include node_modules/testpkg1/dir1 and node_modules/testpkg1/dir2, it gives following error

```
pkg/prelude/bootstrap.js:262
  if (error) throw error;
             ^

Error: Directory '/**/testnodeexe/node_modules/testpkg1/dir1' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:424:17)
    at readdirFromSnapshot (pkg/prelude/bootstrap.js:765:29)
    at Object.fs.readdirSync (pkg/prelude/bootstrap.js:785:12)
    at Object.listdir (/snapshot/testnodeexe/node_modules/testpkg1/lib/util.js:12:5)
    at Object.func1 (/snapshot/testnodeexe/node_modules/testpkg1/index.js:8:14)
    at Object.<anonymous> (/snapshot/testnodeexe/index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1251:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)

```

**Comment by DanielRuf** [comment]
Did you try some glob values like `/**/*/dir1`?

**Comment by yghazi** [comment]
I've encountered the exact same issue.

**Comment by DanielRuf** [comment]
> I've encountered the exact same issue.

Please provide some more information and details so we can reproduce it.

**Comment by DanielRuf** [comment]
> I've encountered the exact same issue.

Saying `I have this problem too` is not very helpful without further information ;-)

**Comment by pkgulati** [comment]
I will try the same

**Comment by Bobur-kobilov** [comment]
@yghazi  Thank you! I solved my issue because of you!
