### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by d2rk87** [vercel/pkg#456]
Use express + sequelize
Error: Cannot find module 'D:\snapshot\thin-client-app-service\node_modules\sql\lib\node\alias'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\snapshot\thin-client-app-service\node_modules\sql\lib\node\binary.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)

**Comment by darrensapalo** [comment]
I think that this is related to [native addons](https://github.com/vercel/pkg/issues/377#issuecomment-643104578).

**Comment by hipstersmoothie** [comment]
closing in favor of #477
