### ISSUE TITLE
issue when execute

### ISSUE THREAD

**Issue by dashng** [vercel/pkg#477]
```
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Cannot find module '/snapshot/cnt-tool/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/cnt-tool/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
```

How to fix this? Any help will be appreciated.

**Comment by dashng** [comment]
```

Error: Cannot find module '/snapshot/cnt-tool/node_modules/sqlite3-promise/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/cnt-tool/node_modules/sqlite3-promise/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
```

**Comment by bjwallwin** [comment]
#471, #120

**Comment by dashng** [comment]
We use docker as our final solution.

Hope pkg can resolve this issue in future.

**Comment by mahyrpt** [comment]
Same issue here as well, any solution?

<pre>
<code>
Error: Cannot find module '\snapshot\wsi\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (\snapshot\wsi\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) 
</code>
</pre>

**Comment by jameswilddev** [comment]
I'm also having this when cross compiling from Ubuntu Trusty x64 on Travis CI to Windows x86 - repro at https://github.com/jameswilddev/vnhtml/commit/a1933e69177d9cc552364467ba957d65c2f21212.

Issues which seem to duplicate this one:
- #456
- #426 
- #424

Seems quite widespread, anyone have any ideas?
