### ISSUE TITLE
Windows - operation not permitted, lstat

### ISSUE THREAD

**Issue by ricsmania** [vercel/pkg#478]
If I use version 4.3.3 or 4.3.2 on Windows 10 x64 I get this error:

> Error! Error: EPERM: operation not permitted, lstat 'C:\MSOCache'
    at Object.lstatSync (fs.js:814:3)
    at exports.lstat (C:\Projetos\testes\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\sync\fs.js:58:20)
    at Object.safeCall [as safe] (C:\Projetos\testes\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\call.js:24:8)
    at stat (C:\Projetos\testes\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\stat.js:19:8)
    at DirectoryReader.processItem (C:\Projetos\testes\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\directory-reader.js:178:5)
    at array.forEach.item (C:\Projetos\testes\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\sync\for-each.js:14:5)
    at Array.forEach (<anonymous>)
    at Object.syncForEach [as forEach] (C:\Projetos\testes\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\sync\for-each.js:13:9)
    at call.safe (C:\Projetos\testes\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\directory-reader.js:87:16)
    at onceWrapper (C:\Projetos\testes\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\call.js:45:17)

The folder that is being read isn't always the same, I noticed it's the first file or folder without privileges, I had hibernation activated before and the error was on hyberfil.sys.

If I try if from another drive letter the error also changes to that letter, for example:

> Error! Error: EPERM: operation not permitted, lstat 'D:\System Volume Information'
    at Object.lstatSync (fs.js:814:3)
    at exports.lstat (D:\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\sync\fs.js:58:20)
    at Object.safeCall [as safe] (D:\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\call.js:24:8)
    at stat (D:\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\stat.js:19:8)
    at DirectoryReader.processItem (D:\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\directory-reader.js:178:5)
    at array.forEach.item (D:\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\sync\for-each.js:14:5)
    at Array.forEach (<anonymous>)
    at Object.syncForEach [as forEach] (D:\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\sync\for-each.js:13:9)
    at call.safe (D:\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\directory-reader.js:87:16)
    at onceWrapper (D:\node-exe\node_modules\@mrmlnc\readdir-enhanced\lib\call.js:45:17)

Version 4.3.1 works fine, but doesn't support Node 10.

**Comment by mikakaraila** [comment]
PKG@4.3.1 seems to work. The latest one fails.

**Comment by saintplay** [comment]
Can confirm this issue, I got

```
> Error! Error: EPERM: operation not permitted, lstat 'C:\Config.Msi'
```

- Node version: 8.12.0

**Comment by anjariamohnish** [comment]
SAME ISSUE I AM FACING

>  Error! Error: EPERM: operation not permitted, lstat 'C:\Config.Msi'
    at Object.fs.lstatSync (fs.js:941:11)
    at exports.lstat (C:\Users\mohnish\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\sync\fs.js:58:20)
    at Object.safeCall [as safe] (C:\Users\mohnish\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\call.js:24:8)
    at stat (C:\Users\mohnish\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\stat.js:19:8)
    at DirectoryReader.processItem (C:\Users\mohnish\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\directory-reader.js:178:5)
    at array.forEach.item (C:\Users\mohnish\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\sync\for-each.js:14:5)
    at Array.forEach (<anonymous>)
    at Object.syncForEach [as forEach] (C:\Users\mohnish\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\sync\for-each.js:13:9)
    at call.safe (C:\Users\mohnish\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\directory-reader.js:87:16)
    at onceWrapper (C:\Users\mohnish\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\call.js:45:17)

**Comment by jaruba** [comment]
has anyone ever found a solution to this issue? i also can't do `fs.readdir()` or `fs.lstat()` on drives from within a packaged `pkg` instance.

i also get the `config.msi` error, and if i ignore it, it still does not acts weirdly and is full of errors

**Comment by robertsLando** [comment]
@erossignon Should be fixed now right?

**Comment by rafadess** [comment]
I'm getting the same issue here when I try to open a file with `fs.promise.open`. Any change news about it?

**Comment by rafadess** [comment]
I'm sorry. After upgrading to the latest version, `5.2.0` the problem is gone. Thank you.
