### ISSUE TITLE
Binding module onoff

### ISSUE THREAD

**Issue by Suprincesu** [vercel/pkg#479]
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 → /snapshot/qms_gpio/node_modules/epoll/build/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/build/Debug/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/build/Release/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/out/Debug/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/Debug/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/out/Release/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/Release/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/build/default/epoll.node
 → /snapshot/qms_gpio/node_modules/epoll/compiled/8.11.3/linux/arm/epoll.node
    at bindings (/snapshot/qms_gpio/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/snapshot/qms_gpio/node_modules/epoll/epoll.js:1:99)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)

**Comment by pcnate** [comment]
no update or fix or anything to this issue? 

Similar issue here:

```
Error: Could not locate the bindings file. Tried:
 → D:\snapshot\redbird_proxy_web\node_modules\deasync\build\deasync.node
 → D:\snapshot\redbird_proxy_web\node_modules\deasync\build\Debug\deasync.node
 → D:\snapshot\redbird_proxy_web\node_modules\deasync\build\Release\deasync.node
```
