### ISSUE TITLE
Unable to load rai.js how to resolve 

### ISSUE THREAD

**Issue by shahajipatil** [vercel/pkg#480]
i have added rai.js in Package.json even i get same issue 
{
"pkg": {
    "scripts": [
      "node_modules/ddos/*.js",
      "node_modules/ddos/**/*.js",
      "node_modules/rai/**/*",
      "node_modules/simplesmtp/**/*"
    ],
    "assets": [
      "node_modules/rai/cert/server.key",
      "node_modules/ddos/**/*.*",
      "node_modules/rai/**/*",
      "node_modules/simplesmtp/**/*"
    ]
  }
pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: File '/**/gammawebsite/node_modules/rai/cert/server.key' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:422:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:646:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:689:18)
    at Object.<anonymous> (/snapshot/gammawebsite/node_modules/rai/lib/rai.js:18:13)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snapshot/gammawebsite/node_modules/simplesmtp/lib/server.js:8:31)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
