### ISSUE TITLE
Issue after upgrading to Next 6.x

### ISSUE THREAD

**Issue by cmosboss** [vercel/pkg#500]
So I have been using PKG for a long time now to deploy my application and I love it. However I noticed after my upgrade to Next Js 6.X I get this error when I try and run my package
```
These dependencies were not found:

* @babel/runtime/helpers/extends in /snapshot/pk-next/node_modules/next/dist/lib/app.js
* webpack-hot-middleware/client?autoConnect=false&overlay=false&reload=true in /snapshot/pk-next/node_modules/next/dist/client/webpack-hot-middleware-client.js

To install them, you can run: npm install --save @babel/runtime/helpers/extends webpack-hot-middleware/client?autoConnect=false&overlay=false&reload=true
(node:15221) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead

```
I get no errors at all during building / packaging just when running the package. Any idea?

After it builds I can still use the application but it spams this at me 
```
{ Error: Cannot find module '/home/cmos/Dev/src/.next/build-manifest.json'
    at Function.Module._resolveFilename (module.js:540:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:583:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at _callee3$ (/snapshot/pk-next/node_modules/next/dist/server/render.js:202:29)
    at tryCatch (/snapshot/pk-next/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/snapshot/pk-next/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.forEach.prototype.(anonymous function) [as next] (/snapshot/pk-next/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/snapshot/pk-next/node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/snapshot/pk-next/node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }
```

My workflow for PKG has been so solid so far I have not really had to mess with it. Hoping I can figure it out since I love this module.

**Comment by zocheyado** [comment]
Something I forgot to note, the pkg log file has no errors whatsoever. Just 
```
> [debug] File %1 added to queue.
> [debug] The file was included as DISCLOSED code (with sources)
etc etc
```

**Comment by zocheyado** [comment]
@igorklopov or anyone else have any direction on this? I use this package regularly and if I can find the fix I will gladly make  PR. I just need some direction on what might be the cause of this.

**Comment by xfumihiro** [comment]
tried setting .babelrc with

```json
"presets": [
  [
    "next/babel",
    {
      "transform-runtime": { "helpers": true, "regenerator": true }
    }
  ]
]
```
and adding @babel/runtime dependency
but no luck

maybe [this](https://github.com/babel/babel/pull/8435) will help

**Comment by xfumihiro** [comment]
Ok, this works:
```json
"pkg": {
    "assets": [
      ".next/**/*",
      "static/**/*"
    ],
    "scripts": [
      ".next/dist/**/*.js",
      "node_modules/@babel/runtime/**/*.js",
      "node_modules/babel-runtime/**/*.js"
    ]
  },
```

**Comment by djskinner** [comment]
If I put the `babel-runtime` stuff in `"assets"` instead of `"scripts"` I can avoid the warnings. Guess my issue with `"next/config"` is a different one.
