### ISSUE TITLE
Permission denied: mkdir /snapshot/project

### ISSUE THREAD

**Issue by fishear** [vercel/pkg#503]
I  run into a problem when I run the generated executable file:

`UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/snapshot/project'
    at Object.fs.mkdirSync (fs.js:874:3)
    at mkdirsSync (/snapshot/project/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at mkdirsSync (/snapshot/project/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:16)
    at mkdirsSync (/snapshot/project/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:38:9)
    at mkdirsSync (/snapshot/project/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:38:9)
    at mkdirsSync (/snapshot/project/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:38:9)
    at mkdirsSync (/snapshot/project/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:38:9)
    at mkdirsSync (/snapshot/project/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:38:9)
    at mkdirsSync (/snapshot/project/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:38:9)
    at mkdirsSync (/snapshot/project/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:38:9)
`

when I add sudo:
new error happens:
`UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir 'xxxxxx'
at Object.fs.mkdirSync (fs.js:874:3)`

Is something wrong with fs.mkdirSync ?

Node: 
v10.7.0

OS: 
darwin
10.13.6

**Comment by sergiz** [comment]
snapshot is a read-only.

**Comment by marjorieRobert** [comment]
I have the same problem.
Did you find a solution?

**Comment by sergiz** [comment]
Don't try to make folder in snapshot, but your actual filesystem?

**Comment by marjorieRobert** [comment]
Thanks for the answer.
I don't want to create snapshot. I don't know what a snapshot is really. 
Where can I say to make folder in actual file system?

This is my conf in package.json : 
{
  "main": "app/js/diabolo.js",
  "bin": "server.js",
  "private": true,
  "dependencies": {
    ..
  },
  "pkg": {
    "assets": [
      "app/**/*",
      "js/**/*",
      "build/**/*",
      "static/**/*",
      "bower_components/**/*",
      "node_modules/**/*"
    ]
  },
  ...
  }
}

**Comment by sergiz** [comment]
1. You should really read the **whole** readme of this package, so you understand how it works.
2. Do not refer to your paths using __dirname (which you will understand why when you finish 1)

**Comment by polkila** [comment]
1. Locate path where you want to make new dir.
2. Add it into assets array.

"pkg": {
    "assets": [
      "tmp/**"
    ]
  },
