### ISSUE TITLE
Can't open '/snapshot/pkg/node_modules/screenshot-stream/stream.js'

### ISSUE THREAD

**Issue by estebanpanelli** [vercel/pkg#540]
Used sample code from screenshot-stream

```
const fs = require('fs')
const screenshot = require('screenshot-stream');
const stream = screenshot('http://google.com', '900x180', {crop: true});
stream.pipe( fs.createWriteStream('google.png')  );
```
runing node index.js works fine

using pkg@4.3.4

when running binary throws:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Can't open '/snapshot/pkg/node_modules/screenshot-stream/stream.js'
    at LineStream.module.exports.byline.on.data (/snapshot/pkg/node_modules/screenshot-stream/index.js:77:16)
    at emitOne (events.js:116:13)
    at LineStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at LineStream.Readable.push (_stream_readable.js:208:10)
    at LineStream.Transform.push (_stream_transform.js:147:32)
    at LineStream._pushBuffer (/snapshot/pkg/node_modules/byline/lib/byline.js:125:17)
    at LineStream._transform (/snapshot/pkg/node_modules/byline/lib/byline.js:116:8)
    at LineStream.Transform._read (_stream_transform.js:186:10)
```

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
