### ISSUE TITLE
Not able to create/unlink folder after packaging the node application and getting below error. Kindly help to resolve this issue and let me know how can i create a folder in "C:\snapshot".

### ISSUE THREAD

**Issue by mukeshthe93** [vercel/pkg#567]
Not able to create/unlink folder after packaging the node application and getting below error. Kingly help to resolve this issue.
Inside err.code !== 'EEXIST', Error mesaage::Error: ENOENT: no such file or directory, unlink 'C:\snapshot\application\userData\checksum.xml'

POST /exportFile 500 7.432 ms - 1295
Error: No default engine was specified and no extension was provided.
    at new View (C:\snapshot\application\node_modules\express\lib\view.js:61:11)
    at Function.render (C:\snapshot\application\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (C:\snapshot\application\node_modules\express\lib\response.js:1008:7)
    at C:\snapshot\application\app.js:40:13
    at Layer.handle_error (C:\snapshot\application\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\snapshot\application\node_modules\express\lib\router\index.js:315:13)
    at C:\snapshot\application\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\snapshot\application\node_modules\express\lib\router\index.js:335:12)
    at next (C:\snapshot\application\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (C:\snapshot\application\node_modules\express\lib\router\layer.js:67:12)

[debug] Targets:
  [
  {
    "nodeRange": "node8",
    "platform": "win",
    "arch": "x64",
    "output": "C:\\Users\\mukesh\\Desktop\\MyApplication\\application.exe",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node8",
      "platform": "win",
      "arch": "x64",
      "forceBuild": false,
      "binaryPath": "C:\\Users\\mukesh\\.pkg-cache\\v2.5\\fetched-v8.11.3-win-x64"
    },
    "binaryPath": "C:\\Users\\mukesh\\.pkg-cache\\v2.5\\fetched-v8.11.3-win-x64"
  }
]

**Comment by marcotuna** [comment]
How are you loading checksum.xml in your NodeJS code?

**Comment by mukeshthe93** [comment]
I have created an XML file using JSON data send by Client (Rest API) and created a checksum.xml file using checksum NPM module and store it in XML file. i.e checksum.xml

**Comment by robertsLando** [comment]
Snapshot is not writable
