### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by ChristianGrieger** [vercel/pkg#589]
Hey all,
I tried to pkg my little nodejs app i coded and after the try to run it this comes up:
```
Error: Cannot find module '/snapshot/cryptobreedables_normal/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```
its pkged with the command -> pkg package.json
this is my package.json
```
{
  "name": "cryptobot",
  "version": "1.0.0",
  "description": "",
  "main": "./index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "bin" : { 
    "cryptobot" : "./index.js" 
  },
  "pkg": {
    "scripts": "./functions/**/*.js",
    "assets": "./storage/**/*"
  },
  "author": "Christian Grieger",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "altcoin-rpc": "^1.0.2",
    "array-unique": "^0.3.2",
    "big.js": "^5.2.2",
    "discord.js": "^11.4.2",
    "jsonfile": "^5.0.0",
    "log4js": "^3.0.6",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.23",
    "mysql2": "^1.6.4"
  }
}
```
and this is my folder structure:
<img width="343" alt="bildschirmfoto 2018-12-19 um 20 23 54" src="https://user-images.githubusercontent.com/8712219/50242951-05fa1d00-03cc-11e9-82b5-06b1ae3937b6.png">

I really hope someone can help me to solve this problem ;)

Thank you!

**Comment by jjalonso** [comment]
Running same error when executing the bin.
I used pkg src/index.mjs

**Comment by jjalonso** [comment]
having same issue

```
Juans-MBP:Work jjalonso$ pkg mr-broker/src/index.mjs --target macos
> pkg@4.4.0
> Warning Failed to make bytecode node10-x64 for file /snapshot/mr-broker/src/index.mjs
> Warning Failed to make bytecode node10-x64 for file /snapshot/mr-broker/src/prompts.mjs
> Warning Failed to make bytecode node10-x64 for file /snapshot/mr-broker/src/api.mjs
```

**Comment by gigouni** [comment]
Hi @jjalonso, 

how did you solve your problem? Could help many people, several issues are opened with the same error message without any actual answer.

Thanks

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
