### ISSUE TITLE
Package MJML to run as standalone

### ISSUE THREAD

**Issue by 0FilipK** [vercel/pkg#618]
Hi, I'm trying to make MJML ( https://mjml.io/ ) package be able to run without node environment. I want to use it in MJML Symfony bundle ( https://github.com/notFloran/mjml-bundle ) and I don't want to install node in my php docker container where I have Symfony project. I decided to generate "standalone" mjml file.

Steps:
`mkdir test && cd test`
`npm install -g pkg`
`npm install mjml`
`cd bin/`
`pkg mjml`

and it's generate 3 files - windows, macos and linux. I'm using MacOS so I typed `./mjml-macos testfile.html`

and terminal says:

`pkg/prelude/bootstrap.js:1178
      throw error;
      ^

Error: Cannot find module './module'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snapshot/test/node_modules/datauri/index.js:10:18)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)`

Any advices?

**Comment by tuandaoidtek** [comment]
"pkg": {
    "assets": [
      "node_modules/datauri/**/*",
      "node_modules/mimer/**/*"
    ],
    "targets": [
      "node8",
      "win"
    ]
  }

add this to package.json
