### ISSUE TITLE
Cannot find module './build/Release/scrypt'

### ISSUE THREAD

**Issue by theone3nu** [vercel/pkg#621]
I am trying to package my nodejs app into executable file.
I did by running this command npx pkg server.js
It generated 3 os executable files.
Window exectuable file is working fine only where the src code is present. I am able to see my server is running on port 3000.
But when i am trying to run linux file in debian os i am getting an error that says Cannot find module './build/Release/scrypt'.

Error: Cannot find module './build/Release/scrypt'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snapshot/esgoserver/node_modules/scrypt/index.js:3:20)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)

Please help. Here is my package.json
```
{
  "name": "server",
  "version": "1.0.1",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.16.4",
    "express-session": "^1.15.6",
    "md5": "^2.2.1",
    "qrcode": "^1.3.2",
    "speakeasy": "^2.0.0",
    "truffle-hdwallet-provider": "^1.0.1",
    "web3": "^1.0.0-beta.37"
  },
  "devDependencies": {
    "nodemon": "^1.18.9"
  }
}
```

Also i have files like json which my node js code is trying to access by calling require('../..data/users.json')

**Comment by callmenick** [comment]
This isn't a `next` issue, it's a web3 issue or potentially webpack issue. You'll need to let webpack resolve `.node` file extensions.
