### ISSUE TITLE
Error on Alpine 

### ISSUE THREAD

**Issue by sdomotica** [vercel/pkg#625]
I'm pkg a simple js file just consolelog("test") in a docker image.
I'm using raspberry 3b
Host: Linux b7f4433c11a6 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l Linux
Docker image used:  "Alpine Linux v3.9"
Node version: v10.14.2
PKG: pkg@4.3.7

I run this command
pkg time.js  -t node10-alpine-x64 -o test

and I have this error:

pkg time.js  -t node10-alpine-x64 -o test
> pkg@4.3.7
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.4.1-alpine-x64   [====================] 100%
internal/child_process.js:358
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:538:9)
    at fabricate (/usr/lib/node_modules/pkg/lib-es5/fabricator.js:73:54)
    at fabricateTwice (/usr/lib/node_modules/pkg/lib-es5/fabricator.js:139:3)
    at MultiStream._queue (/usr/lib/node_modules/pkg/lib-es5/producer.js:120:53)
    at MultiStream._next (/usr/lib/node_modules/pkg/node_modules/multistream/index.js:73:10)
    at Meter.onEnd (/usr/lib/node_modules/pkg/node_modules/multistream/index.js:120:10)
    at Object.onceWrapper (events.js:273:13)
    at Meter.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)

**Comment by anurbol** [comment]
Any updates?

**Comment by erosval** [comment]
Maybe this can be useful for you: [Deploy a commercial Next.js application with pkg and docker](https://medium.com/@evenchange4/deploy-a-commercial-next-js-application-with-pkg-and-docker-5c73d4af2ee)
