### ISSUE TITLE
libxml error when running as an exe

### ISSUE THREAD

**Issue by psaxena** [vercel/pkg#654]
I am creating 64 bit exe for windows for my express app. The app uses libxml module and runs fine. When i compile the app as an exe and run it. It gives below error:

`error: uncaughtException: Could not locate the bindings file. Tried:
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\build\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\build\Debug\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\build\Release\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\out\Debug\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\Debug\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\out\Release\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\Release\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\build\default\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\compiled\10.4.1\win32\x64\xmljs.node
Error: Could not locate the bindings file. Tried:
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\build\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\build\Debug\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\build\Release\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\out\Debug\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\Debug\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\out\Release\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\Release\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\build\default\xmljs.node
 → E:\SmartTicket WorkSpace\AnalyzerBinary\node_modules\libxmljs\compiled\10.4.1\win32\x64\xmljs.node
    at bindings (E:\snapshot\Analyzer\node_modules\bindings\bindings.js:96:9)
    at Object.<anonymous> (E:\snapshot\Analyzer\node_modules\libxmljs\lib\bindings.js:3:43)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)`

Any idea what could be going wrong. If I am required to add some file name in package.json for this?

**Comment by psaxena** [comment]
Solved by copying xmljs.node to root folder of binary app
