### ISSUE TITLE
Issue within local network

### ISSUE THREAD

**Issue by ctlkkc** [vercel/pkg#674]
I have no external network access but have my node's source - wanted to build locally by passing --build option but still failed:

```
$ ./node_modules/.bin/pkg . --build -t node8-linux-x64
> pkg@4.3.8
> Building base binary from source:
  built-v8.11.3-linux-x64
> Cloning Node.js repository from GitHub...
  git                          [                    ] 0%Cloning into bare repository 'node/.git'...
fatal: unable to access 'https://github.com/nodejs/node/': Could not resolve host: github.com
  git                          [====================] 100%
> Error! Error: git failed with code 128
    at ChildProcess.<anonymous> (/local/data/scratch/services/webservice/raptor_statistics_dashboard/pack_test/package/node_modules/pkg-fetch/lib-es5/spawn.js:73:23)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

What the doc tell me is:  If you prefer to compile base binaries from source instead of downloading them, you may pass --build option to pkg. First ensure your computer meets the requirements to compile original Node.js: BUILDING.md
How should I understand that and make it work?

Thanks

**Comment by ctlkkc** [comment]
Any update? Thanks
