### ISSUE TITLE
Cant find native build for platorm win32 when using the leveldown pkg

### ISSUE THREAD

**Issue by cocoonyou** [vercel/pkg#758]
Back in 2017 you added support for it somewhere along the lines it got messed up.
Error: 
`(node:26872) UnhandledPromiseRejectionWarning: Error: No native build was found for platform=win32 arch=x64 runtime=node abi=64 uv=1 libc=glibc
    at Function.load.path (C:\snapshot\lockedware\node_modules\node-gyp-build\index.js:56:9)
    at load (C:\snapshot\lockedware\node_modules\node-gyp-build\index.js:20:30)
    at Object.<anonymous> (C:\snapshot\lockedware\node_modules\leveldown\binding.js:1:105)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)`

You can re-create this by simply trying to get a id from level down will work in testing but not in compiled @zeit-test 
"support you added": https://github.com/zeit/pkg/blob/master/test/test-79-npm/leveldown/leveldown.js

**Comment by cocoonyou** [comment]
bippity BOP bump?

**Comment by ukaric** [comment]
I have same issue with leveldown resolution.

**Comment by soapdog** [comment]
This is still an issue. It would be great if the workflow for using native modules was better or at least better documented.

**Comment by serra82** [comment]
Did you add:  
"assets": [ "node_modules/leveldown/**/*" ]
 in package.json?

**Comment by taratatach** [comment]
@serra82 I can't find any `assets` configuration key. Did you mean `files`?

In any case, why would this be required for win32 while it works perfectly fine on win64 without it?

Thanks for the suggestion though, I'll try it anyway :).
