### ISSUE TITLE
Convert browserify to an exe fails with --build option

### ISSUE THREAD

**Issue by iniatse** [vercel/pkg#772]
```
pkg node_modules/browserify --targets latest --build
> pkg@4.4.0
> Building base binary from source:
  built-v12.2.0-win-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v12.2.0
> Applying patches

> Error! Error: spawn patch ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

Am I doing something wrong or is this a bug?

**Comment by roberto-slopez** [comment]
Not sure if version 12.2.0 is supported, I use node10-win-x64 and it works fine
