### ISSUE TITLE
Problem with worker_threads

### ISSUE THREAD

**Issue by pacop** [vercel/pkg#775]
SO: Windows 7 and Ubuntu 18.04
Node: v12.2.0
Architecture: x86

```javascript
//package.json
{
  "name": "a",
  "version": "0.1.0",
  "description": "proof",
  "bin": "a.js",
  "license": "UNLICENSED",
  "devDependencies": {
    "pkg": "^4.4.0"
  },
  "pkg": {
    "scripts": ["a.js","b.js"]
  }
}

```

```javascript
// a.js
console.log("Starting a");
const {Worker} = require('worker_threads');
new Worker('./b.js');
console.log("Finishing a");
```

```javascript
// b.js
console.log("Starting b");
console.log("Finishing b");
```

Expected result (obtained running `node a.js`):
```
Starting a
Finishing a
Starting b
finishing b
```

Result obtained using executable file generated by pkg:
```
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
Finishing a
Starting a
(infinite loop)
#
# Fatal process OOM in insufficient memory to create an Isolate
#
<--- Last few GCs --->
<--- JS stacktrace --->
Segmentation fault
```

**Comment by pacop** [comment]
SO: Windows 7 and Ubuntu 18.04
Node: v10.15.3
Architecture: x86

```
$ ./a.exe
Starting a
Finishing a
pkg/prelude/bootstrap.js:52
    throw new Error('PKG_DUMMY_ENTRYPOINT EXPECTED');
    ^

Error: PKG_DUMMY_ENTRYPOINT EXPECTED
    at C:\snapshot\prueba\a.js.0 (pkg/prelude/bootstrap.js:52:11)
    at pkg/prelude/bootstrap.js:1516:3
    at readPrelude (internal/bootstrap/node.js:240:16)
    at internal/bootstrap/node.js:245:22
    at internal/bootstrap/node.js:252:8
    at startup (internal/bootstrap/node.js:253:6)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)
```

**Comment by pacop** [comment]
The issue still remains unfixed in current version.

**Comment by robertsLando** [comment]
@jesec @erossignon thoughts on this?

**Comment by erossignon** [comment]
For me,  it cannot be reproduced with the lastest main branch and may have been fixed somehow already.
@pacop , please challenge the unit test I wrote to help us reproduce.

**Comment by robertsLando** [comment]
Dup of #716
