### ISSUE TITLE
pkg . --targets node10-win-x86 will show spawn error, won't work

### ISSUE THREAD

**Issue by guillempascual** [vercel/pkg#828]
If you try to package to a windows x86 target, it won't work. To the x64 it works fine.

When doing a   
`pkg . --targets node10-win-x86 `

will show an error

```
> pkg@4.3.8
internal/child_process.js:371
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:371:11)
    at spawn (child_process.js:561:9)
    at fabricate (/usr/local/lib/node_modules/pkg/lib-es5/fabricator.js:73:54)
    at fabricateTwice (/usr/local/lib/node_modules/pkg/lib-es5/fabricator.js:139:3)
    at MultiStream._queue (/usr/local/lib/node_modules/pkg/lib-es5/producer.js:120:53)
    at MultiStream._next (/usr/local/lib/node_modules/pkg/node_modules/multistream/index.js:73:10)
    at Meter.onEnd (/usr/local/lib/node_modules/pkg/node_modules/multistream/index.js:120:10)
    at Object.onceWrapper (events.js:281:20)
    at Meter.emit (events.js:193:13)
    at endReadableNT (_stream_readable.js:1139:12)
```
System: Mac OS Catalina
Node version: 11.15 (I downgraded to 10 with same result)
npm version : 6.7.0
pkg version: 4.3.8 (tried older and newer ones)

**Comment by marcelofarias** [comment]
Probably related to this: "Starting with macOS Catalina, 32-bit apps are no longer compatible with macOS" https://support.apple.com/en-us/HT208436

**Comment by mreis1** [comment]
It has to be related with Catalina. Before updating my system, pkg was working for (win-x86) and since I didn't update pkg, the system update I made has to be cause. 

My work around was to use my windows VM to pkg my app.

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
