### ISSUE TITLE
fs.rmdir recursive stops working after app is packaged

### ISSUE THREAD

**Issue by LinkTree3** [vercel/pkg#887]
The following script works in 2 cases:
1. The script is ran unpackaged directly from node as `node test.js` and works perfectly
2. The script is ran packaged and the tmpDir is empty. (most remove/comment fs.appendFileSync line)
```
const os = require('os');
const fs = require('fs');
const path = require('path');

var tmpDir = path.join(os.tmpdir(), 'test');
if(!fs.existsSync(tmpDir)){
    fs.mkdirSync(tmpDir);
    fs.appendFileSync(path.join(tmpDir, 'message.txt'), 'data to append');
}

fs.rmdir(tmpDir, {recursive: true}, function(err){
    if(err) throw err;
    console.log('finished');
});
```

Otherwise it returns the following error;

```
internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Buffer
    at validateString (internal/validators.js:117:11)
    at Object.dirname (path.js:583:5)
    at isRootPath (pkg/prelude/bootstrap.js:168:26)
    at fs.readdir (pkg/prelude/bootstrap.js:850:18)
    at _rmchildren (internal/fs/rimraf.js:130:3)
    at internal/fs/rimraf.js:117:16
    at FSReqCallback.oncomplete (fs.js:154:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

This leads me to believe fs.rmdir recursion is bugged in the patched pkg executables.

Tested on node12 and 13 on Windows 10 with pkg version 4.4.6

**Comment by LinkTree3** [comment]
I ended up using the `del` package.
recursion can also be done by hand like this

```
var fs = require('fs');
var deleteFolderRecursive = function(path) {
  if( fs.existsSync(path) ) {
    fs.readdirSync(path).forEach(function(file,index){
      var curPath = path + "/" + file;
      if(fs.lstatSync(curPath).isDirectory()) { // recurse
        deleteFolderRecursive(curPath);
      } else { // delete file
        fs.unlinkSync(curPath);
      }
    });
    fs.rmdirSync(path);
  }
};
```

**Comment by MaduekwePedro** [comment]
still having the same issue
