### ISSUE TITLE
Does not compile libxmljsmodule for linux

### ISSUE THREAD

**Issue by psaxena** [vercel/pkg#911]
Hi,

I am using "pkg" node module to compile my node application into exe for windows and linux. I am able to run my app on windows using "xmljs.node" along with node-app.exe in same folder.. But on linux, I get error :

`[[31merror[39m]: uncaughtException: /root/ResourceService/xmljs.node: invalid ELF header
Error: /root/ResourceService/xmljs.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:729:18)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/snapshot/ResourceService/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/snapshot/ResourceService/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)`

What could be the way to get this working?
Does pkg module take care of handling node modules for linux when we pass linux as target? Or do i need to compile my app on linux in order to get that?

**Comment by hipstersmoothie** [comment]
No reproduction repo. If the issue persists feel free to open a new issue with a reproduction repo!
