### ISSUE TITLE
Not able to create executable on Power 9 machine [ppc64le]

### ISSUE THREAD

**Issue by narkhedek3** [vercel/pkg#924]
Following error I am getting when I have tried to create executable on ppc64le machine--

> pkg@4.4.8
> Targets not specified. Assuming:
  node14-linux-ppc64, node14-macos-ppc64, node14-win-ppc64
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.0.0-linux-ppc64  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v14.0.0-linux-ppc64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.0.0-linux-ppc64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.0.0-linux-ppc64"}
> Building base binary from source:
  built-v14.0.0-linux-ppc64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v14.0.0
> Applying patches
> Compiling Node.js from sources...
  make                         [                    ] 0%                                                                  ^
../src/env-inl.h: In constructor ‘node::AllocatedBuffer::AllocatedBuffer(node::AllocatedBuffer&&)’:
../src/env-inl.h:981:23: error: no matching function for call to ‘node::AllocatedBuffer::AllocatedBuffer()’
     : AllocatedBuffer() {
                       ^
../src/env-inl.h:981:23: note: candidates are:
In file included from ../src/env-inl.h:28:0,
                 from ../src/api/async_resource.cc:2:
../src/env.h:576:10: note: node::AllocatedBuffer::AllocatedBuffer(node::AllocatedBuffer&&)
   inline AllocatedBuffer(AllocatedBuffer&& other);
          ^
../src/env.h:576:10: note:   candidate expects 1 argument, 0 provided
In file included from ../src/api/async_resource.cc:2:0:
../src/env-inl.h:948:8: note: node::AllocatedBuffer::AllocatedBuffer(node::Environment*, uv_buf_t)
 inline AllocatedBuffer::AllocatedBuffer(Environment* env, uv_buf_t buf)
        ^
../src/env-inl.h:948:8: note:   candidate expects 2 arguments, 0 provided
make[1]: *** [/tmp/GBfP9xHfUJV2aetoX1Cg/node/out/Release/obj.target/libnode/src/api/async_resource.o] Error 1
make[1]: Leaving directory `/tmp/GBfP9xHfUJV2aetoX1Cg/node/out'
make: *** [node] Error 2
  make                         [====================] 100%
> Error! Error: make failed with code 2
    at ChildProcess.<anonymous> (/home/parade/node/node-v14.3.0-linux-ppc64le/lib/node_modules/pkg/node_modules/pkg-fetch/lib-es5/spawn.js:68:23)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by narkhedek3** [comment]
Issue is resolved problem. I have changed my node version after that it is working..😁
