### ISSUE TITLE
odd behaviour with assets

### ISSUE THREAD

**Issue by Impeekay** [vercel/pkg#933]
I was trying to work with `appmetrics` package. running into some issue while running it especially [here](https://github.com/RuntimeTools/appmetrics/blob/4862e6882e85b63ea22c55cb4b273f17ef4820cb/index.js#L295) 

The stack trace
```
[Thu Jun 18 16:15:59 2020] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 5.1.1.202006181050 (Agent Core 4.0.5)
[Thu Jun 18 16:15:59 2020] com.ibm.diagnostics.healthcenter.loader WARNING: Failed to open library /snapshot/insite-server/node_modules/appmetrics/plugins/libhcapiplugin.so:/snapshot/insite-server/node_modules/appmetrics/plugins/libhcapiplugin.so: cannot open shared object file: No such file or directory
[Thu Jun 18 16:15:59 2020] com.ibm.diagnostics.healthcenter.loader WARNING: Failed to open library /snapshot/insite-server/node_modules/appmetrics/plugins/libhcapiplugin.so:/snapshot/insite-server/node_modules/appmetrics/plugins/libhcapiplugin.so: cannot open shared object file: No such file or directory
[Thu Jun 18 16:15:59 2020] com.ibm.diagnostics.healthcenter.loader WARNING: Failed to open library /snapshot/insite-server/node_modules/appmetrics/plugins/libhcapiplugin.so:/snapshot/insite-server/node_modules/appmetrics/plugins/libhcapiplugin.so: cannot open shared object file: No such file or directory
[Thu Jun 18 16:15:59 2020] com.ibm.diagnostics.healthcenter.loader WARNING: Failed to initialize monitoring API
2020-06-18 16:15:59 error: uncaughtException: Monitoring API is not initialized
Error: Monitoring API is not initialized
    at new API (/snapshot/insite-server/node_modules/appmetrics/appmetrics-api.js:238:9)
    at Object.getAPI (/snapshot/insite-server/node_modules/appmetrics/appmetrics-api.js:248:10)
    at Object.monitor (/snapshot/insite-server/node_modules/appmetrics/index.js:295:24)
    at appMetrics (/snapshot/insite-server/build/helpers/statsd/appMetrics.js:11:30)
    at Object.<anonymous> (/snapshot/insite-server/build/index.js:27:1)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
```
As I can see it is unable to use the shared object file in the plugins directory, but I've explicitly added them into the pkg by mentioning them as assets in package.json
```
 "pkg": {
    "assets": [
      "node_modules/appmetrics/plugins/*"
    ]
```

I'm not sure, what is going wrong. Any help would be appreciated.

**Comment by dstampfer** [comment]
I also have an issue with assets. To me, it seems that the asset config is completeley ignored?

**Comment by CombatCode** [comment]
@dstampfer at least you saved my time, thank you bro

**Comment by Impeekay** [comment]
@dstampfer cool thanks, I'll take a look at that
