### ISSUE TITLE
childProcess exec() fails on packaged app, but ok when run as node app

### ISSUE THREAD

**Issue by diginfo** [vercel/pkg#966]
Been trying to debug this all day, this command works fine when the app is executed using node, or when it is executed in the console, but when it is packaged up and executed it refuses to execute.

And the error data is not really very helpful, it simply says that the command failed, and as far as I can see there's no indication as to why !

```
function exec(cmd,cb){
	var childProcess = require('child_process');
	childProcess.exec(cmd,function (error, stdout, stderr) {
		if(typeof(cb)=="function") {
			if(error){ return cb({error:true,'err':error,'std':stderr,'msg':stderr});}
			else return cb(stdout);
		} else return null;
	});
};
```

```
at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
     killed: false,
     code: 77,
     signal: null,
     cmd: '/usr/lib/libreoffice/program/soffice.bin --headless --convert-to pdf --outdir /usr/share/dev/nodejs/src/xx/data/public/udata/ /usr/share/dev/nodejs/src/xx/data/public/files/1597894080138.xlsx' },
  std: '',
  msg: '' }

```

any idea on what the issue may be ?

**Comment by diginfo** [comment]
Solved, this had nothing to do with pkg, and was related to the home folder of the user, although I don't know why it did not pickup the default.

export HOME=/myhome && /usr/lib/libreoffice/program/soffice.bin --headless --convert-to pdf --outdir /usr/share/dev/nodejs/src/xx/data/public/udata/ /usr/share/dev/nodejs/src/xx/data/public/files/1597894080138.xlsx
