### ISSUE TITLE
Error: File was not included into executable at compilation stage. Please recompile adding it as asset or script.

### ISSUE THREAD

**Issue by 4567q** [vercel/pkg#968]
Can't solve the problem what could be the matter

`[Модули]: Отсутствуют зависимости, перезапустите программу или обратитесь за помощью к разработчику
Error: File 'C:\**\BoostMachine\node_modules\steam-client\steam-resources\steam_language_parser\steammsg.steamd' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:426:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:654:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:698:18)
    at Object.<anonymous> (C:\snapshot\BoostMachine\node_modules\steam-client\steam-resources\steam_language_parser\index.js:7:71)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31) {
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\snapshot\\BoostMachine\\node_modules\\steam-client\\steam-resources\\steam_language_parser\\steammsg.steamd',
  pkg: true
}`

package.json

`{
  "name": "BoostMachine",
  "version": "1.0.2",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "request-promise": "^4.2.2",
    "steam-totp": "^2.1.0",
    "steam-tradeoffer-manager": "^2.9.4",
    "steam-user": "^3.29.1",
    "steamcommunity": "^3.38.0",
    "winston": "^3.1.0",
    "moment": "^2.22.2",
    "request": "2.88.0"
  },
  "bin": "./index.js",
  "pkg":{
  	"assets"  : "./node_module/steam-client/node_modules/config/**/*.*",
  	"scripts" : "./app/app.js",
    "scripts" : "./app/infolog.js",
    "scripts" : "./app/methods.js",
    "scripts" :  "./app/steam.js",
    "scripts" : "./app/Settings/config.js"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
   "repository": {
    "type": "git",
    "url": ""
  },
  "author": "qqerw4",
  "license": "MIT"
}`

**Comment by nirmal98kumar** [comment]
Same kinda issue I am facing .

**Comment by hipstersmoothie** [comment]
No reproduction repo. If the issue persists feel free to open a new issue with a reproduction repo!
