### ISSUE TITLE
Cannot support ES8 Optional chaining (?.)

### ISSUE THREAD

**Issue by axolo** [vercel/pkg#984]
```js
D:\snapshot\lpcheer-api\app\controller\feedback.js:35
    const userId = state.auth?.userId;
                              ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:89:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by josiahbryan** [comment]
I personally use rollup/babel to build/transpile my code into a "more widely supported" version before using pkg - this could help you.

Personally, I write all my code using the latest supported node at work (Node 12 in my case), but for our target devices, we have to use Node 8 (due to GCC ver on the embedded device.)

Therefore, I use rollup to transpile my development code down to something that runs on Node 8, and then use `pkg` to target node 8 / armv7 for the final binary.

YMMV, HTH.

**Comment by hipstersmoothie** [comment]
Just choose a binary that support optional chaining or transpile your code before running `pkg`
